export default {
    apply:'申請を出す',
    qus:'あなたの質問を選んでください',
    email:'eメールを入力してください',
    des:'あなたの質問を述べてください',
    img:'スクリーンショットをアップロードする',
    qus1:'検証問題',
    qus2:'充電',
    qus3:'提現',
    qus4:'受注',
    qus5:'取引',
    qus6:'口座',
    qus7:'他の',
    submit:'提出',
    success:'提出成功',
    phone:'電話を入力してください',
}