export default {
   
  Popover_Quantity:'数',
  Popover_Amount:'総額',
  Popover_Average:'平均価格',
  PleaseLogin:'先に登録してください',
  PleasePass:'取引パスワードを入力してください',
  theme: 'テーマカラー',
  dark: '黒',
  light: '亮',
  time: '时间',
  price0: '価格',
  amount1: '成約数量',
  buy: '買い入れ',
  sell: '売れ',
  bestBuy: '最適買値',
  bestSell: '最適売価',
  totalAmont: '金額',
  depth: '深さ',
  deposit: '充電',
  property: '私の資産',
  free: '手数料',
  priceWarn: '価格入力は必須です',
  numWarn: '依頼数が低すぎるか、超過する',
  login: 'ログイン',
  priceNull: '依頼価格を入力してください',
  numNull: '依頼件数を入力してください',
  priceError: '価格の誤り',
  petl:'依頼価格が制限を超える',
  openPrice1:'生まれ',
  Limit1:'上限制',
  numError: '数の間違い',
  pwdNull: '取引パスワードを入力してください',
  available: '可用',
  open: '成約しない依頼',
  tr: '成約の記録',
  type: 'タイプ',
  price: '価格',
  price3: '委託価格',
  price2: '成約価格',
  amount: '数',
  Or:'依頼する',
  amount3: '依頼数',
  status: '状态',
  action: '操作',
  total: '依頼金額',
  filled: '已成約数量',
  tPwd: 'トランザクション暗号',
  bPwd: 'パスワード',
  ok: '确认',
  before: '取引の前にどうぞ',
  unfinished: '成約がない',
  register: '登録',
  or: 'または',
  pfinished: '部分成約',
  cancel: '撤去単',
  completed: 'すべて成約する',
  more: 'より',
  cancelOk: '単撤収成功',
  price1: '限價',
  lPrice: '時価',
  equate: '买できる',
  equate1: '売るできる',
  lPriceMes: `<p>市价指不设定买入价格或卖出价格，按照</p>
    <p>当前的市场价格买入或卖出，只需输入想</p>
    <p>买入的总金额或卖出的总数量即可</p>`,
    transactionaAount: '成約金額',
    remainingAmount: '未成約数量',
    all: '全部',
    ipe: 'メールボックスや携帯電話',
    ippwd: 'パスワード',
    fpws: 'パスワードを忘れる',
    rg: '即時登録',
    Average:'成約平均',
    Turnover:'出来高',
    transactions:'取引數量',
    Batch:'大量離脱',
  delegation:'注文',
  transaction:'成交',
  pletPwd:'取引パスワードを入力してください!',
  orclsPwd:'パスワードを消すかどうかです',
  cancleok:'一括取り消し中です',
  cancleok2:'つの依頼書,',
  cancleok3:'撤回を確定するか?',
  contentPool:'プラットフォーム取引手数料は、2018年12月1日から2019年3月31日までの期間、取引手数料の75%減免と、2018年12月1日から31日までの期間に適用される。取引手数料50%減免、2019年1月1日~ 31日取引手数料30%減免、2019年2月1日から28日まで。取引手数料は2019年3月1日から31日まで10%減免される。',
  chexFee:'CHEXを使って取引手数料を差し引く',
  di:'第',
  tian:'日',
  nowShow:'当日は展示',
  decimals:'位小数',
  vol24h: '出来高',
  depthtotal:'出来高',
  Market:'市場',
  
  Yours:'私の',
}