export default {
    feedback:'フィードバック記録',
    qus:'質問タイプ',
    dec:'問題記述',
    qus1:'検証問題',
    qus2:'充電',
    qus3:'やり取りするだけ',
    qus4:'受注',
    qus5:'取引',
    qus6:'口座',
    qus7:'其他',
    upload:'写真をアップロードする',
    me:'私が',
    service:'コール',
    say:'何かを言う',
    ask:'追及',
}