import Header from './header'

export default {
    ...Header,
    hp: '助けて',
    text_1:'コールセンター:+852 2561 1995',
    text_2:'市場協力:+852 2562 9855',
    address:'香港銅鑼湾は223号の海聯大厦に連絡した',
    nr: '登録者数',
    business:'ビジネス提携',
    notice:'法律声明',
    rate:'料率説明',
    privacy:'プライバシー条項',
    us:'私たちについて',
    download:'Android(ポイントダウンロード)',
    ios:'IOS(ポイントダウンロード)',
    load:'本地下載',
    email_1:'support-cn@chaoex.com.hk',
    email_2:'business-cn@chaoex.com.hk',
    unusual: 'トランザクション例外処理',
    API:'APIドキュメント',
    dw:'充值&提現',
    dh:'チャージ記録',
    wh:'引き出し記録',
    fd:'資産管理',
    ac: '個人センター',
    ss: '安全設定',
    vd: '実名認証',
    od: '依頼する',
    th: '取引記録。',
    center:'サポートセンター',
    announcement:'公告',
    faq:'faq',
    code:'CODEについて',
    apidoc: 'API申請',
    transaction:'依頼記録',
    companyEmail:'サービスメール',
    bussinessWith:'ビジネス提携',
    cnuri:'support-cn@chaoex.com.hk',
    cnbus:'business-cn@chaoex.com.hk',
    ng: 'カーナビ',
    down: '下載客戶端',
    fl: '注目',
    procenter:'資産センター',
    info:'BTCインフォメーション',
    risk:'リスク開示',
    pow:'POWコモンズのメンバー', 
    jui:'もしあなたもブロックチェーンに興味があるならば、あなたの参加を歓迎します!',
    Applytolist:'上幣申請',
}