import Header from './header'

export default {
    ...Header,
    hp: '幫助',
    text_1:'客服熱線：+852 2561 1995',
    text_2:'市場合作：+852 2562 9855',
    address:'香港銅鑼灣告士打道223號海聯大廈',
    nr: '註冊人數',
    business:'商務合作',
    notice:'法律聲明',
    rate:'費率說明',
    privacy:'隱私條款',
    us:'關於我們',
    download:'Android（點此下載）',
    ios:'IOS（點此下載）',
    load:'本地下載',
    email_1:'support-cn@chaoex.com.hk',
    email_2:'business-cn@chaoex.com.hk',
    unusual: '交易異常處理',
    API:'API 文档',
    dw:'充值&提現',
    dh:'充值記錄',
    wh:'提现記錄',
    fd:'资产管理',
    ac: '個人中心',
    ss: '安全设置',
    vd: '實名認證',
    od: '委託',
    th: '交易記錄',
    center:'支持中心',
    announcement:'公告',
    faq:'FAQ',
    code:'關於CODE',
    apidoc: 'API 申請',
    transaction:'委托記錄',
    companyEmail:'服務郵箱',
    bussinessWith:'商務合作',
    cnuri:'support-cn@chaoex.com.hk',
    cnbus:'business-cn@chaoex.com.hk',
    ng: '導航',
    down: '下載客戶端',
    fl: '關注',
    procenter:'資產中心',
    info:'BTC 資訊',
    risk:'風險披露',
    pow:'POW共識聯盟成員', 
    jui:'如果您也對區塊鏈感興趣的話，歡迎您的加入！',
    Applytolist:'上幣申請',
}