export default {
    confirmSub:'確定',
    PerCen:'個人センター',
    DownApp:'1.インストールアプリをダウンロードする',
    sQc:'2.二次元コードをスキャンする',
    BK:'3.バックアップキー',
    OpenG:'4. googleの検証を開く',
    HaveApp:'アプリをインストールしました',
    HaveQR:'私は2次元コードのスキャンを終えました',
    HaveKey:'16個の鍵を記憶しています',
    Next:'次のステップ',
    CloseGA: 'googleの検証を停止する',
    login: 'ログインパスワード',
    gaCode: 'google検証コード',
    submit: '解を束ねて',
    bindGA: 'バインディングgoogle検証',
    download: 'googleベリファイアをインストールするAPPをダウンロードする',
    clickDownload: '点このダウンロード',
    scanCode: '下2次元コードをgoogleベリファイアAPPでスキャンする',
    secretKey: '鍵',
    enterPassword: '16個の鍵を紙に正確に記録し、保管してください。もし携帯電話が紛失した場合、この鍵を使ってgoogleの検証を再開することができます',
    enterCode: 'google検証コード',
    modalText: 'アカウントの安全のために二次検証を開くことを強くお勧めします。',
    modalText1: 'ご希望の二次検証方式を選択してください',
    iKnow: '我已知曉風險，',
    noSet: '設置せず',
    bindMess: '2次元コードをスキャンすることができない場合は、手動でgoogle検証アプリに鍵を入力します',
    bindMess1: 'や入力キー',
    tips: 'スイート・ヒント',
    bindPhone:'バインディング携帯',
    bg:'携帯電話の番号は既にバインドされている',
    bag:'google認証のバインディング',
    guAuthPwd:'ログインパスワードを記入してください',
    guAuthCode:'請填寫google検証コード',
    next:'次のステップ',
    nostrum:'googleの検証を人工的な顧客サービスでリセットするには、ワークシートを提出しなければならず、少なくとも7日かかる可能性があります',
    way:'検証方式',
    Vemail:'メールボックス検証',
    VSMS:'携帯電話の検証',
    AVC:'検証コードを取得する',
    pl:'選んでください',
    errorMsg:'検証コードに誤りがある',
    dts:'ちょっと引っ張る',
    dtr:'右にドラッグする',
    uf:'ロード失敗',
    uld:'ローディング中',
    civ:'CHAOEXは検証不能である',
    ck:'知能検査で',
    vs:'検証に成功する',
    vf:'検証失敗',
    vip:'検証中',
    mnn:'メールボックスを空にしてはいけません',
    pnn:'携帯電話を空にしてはいけない',
    send:'送信',
    successGa:'グーグル検証、3s後に「個人センター」に戻る',
    errorGa:'グーグル検証失敗、3s後に「個人センター」に戻る',
    successClose:'グーグル、3s後に「個人センター」に戻る',
    errorClose:'グーグル、3s後に「個人センター」に戻る',
    sv:'検証コードを取得する',
}