export default {
    tc: '取引センター',
    h: 'トップページ',
    lg: 'ログイン',
    rg: '登録',
    fd: '資産管理',
    dw: 'チャージ&アブダクション',
    dh: 'チャージ記録',
    wh: '引き出し記録',
    th: '取引記録。',
    pi: '個人',
    od: '依頼する',
    ns: '助けて',
    Mining_commune: '公社の鉱',
    center:'サポートセンター',
    ac: '個人センター',
    lgt: '退出',
    ss: '安全設定',
    vd: '實名認證',
    logout: '脱退成功',
    announcement:'公告',
    invite:'親友を招く',
    aboutCode: 'CODEについて' ,
    gawt:'取引依頼記録',
    app:'まずアプリの操作に行って、あなたの理解と支持に感謝します!',
    s:'設置',
    theme:'テーマ',
  black:'黒い',
  white:'白い',
  cur:'法幣切替',
  submit: '確認',
  getsuccessed:'受領成功',
    discount:'折扣申購',
    newCoin:'打新区',
    bbwd:'BTC割引キャンペーン',
    endtime:'イベント終了時間',
    day:'日',
    alq:'可用於鎖定:',
    afpq:'申し込み可能:',
    number:'數量',
    lockedn:'今回のロック数',
    lock:'鎖定',
    pci:'今回の請約資格情報',
    token:'トークン名',
    cl:'流通量',
    apq:'申し込み可能数量',
    ql:'数/くじ',
    pp:'申し込み価格/枚',
    op:'生まれ生まれ',
    mwl:'単一口座の最大当選数',
    petnop:'申し込み数量を入力してください',
    purchase:'申購',
    mpr:'私の申し込み記録',
    data:'申購日期',
    spl:'当選当選数',
    ta:'総額',
    ad:'活動細則',
    ls:'鎖定成功',
    ps:'申し込みに成功する',
    st:'現物取引',
    iusertotal:'総有効ユーザ数を招待する',
    usdtPur:'USDT申購',
  chexPur:'CHEX申し込み',
  CHEX_Loan:'chex貸借',
  Follow:'コミュニティ',
  Support:'工単',
  Locked_assets_revenue:'安定した宝。',
  Assets_revenue:'閃息宝',
  Fiat_Convert:'法幣取引',
  Financial_Center:'理財センター',
  alert: 'KYC2認証を先に行ってください',
  PleaseLogin:'先に登録してください',
  PleasePhone:'携帯電話の番号を先にバインドしてください',
  imgUrl:'https://coinmarketcap.com/zh/exchanges/chaoex/',
  whitepaper:'白書',
}
