export default {
  title: 'ログイン',
  welcomeLogin: 'ログイン歓迎',
  ipe: 'メールボックスや携帯電話',
  ippwd: 'パスワード',
  ipvc: '検証コード',
  fpws: 'パスワードを忘れる',
  notIn: '未開設口座',
  rg: '登録',
  lm: '*記入ミス',
  service:'公式サービス・コミュニケーショングループ',
  gaCode: 'google検証コード',
  submit: '確認提出',
  userNameWarn: '*大陸部以外のユーザーの携帯電話登録時は局番を記入してください',
  onelogin:'CHAOEX Appを使ってコードをスキャンし、一歩登録する',
  timeout:'二次元コードはタイムアウトしますので、リフレッシュをクリックしてください',
  sanl:'スキャンコード登録',
  pdl:'パスワード登録',
  accl:'アカウント登録',
  noapp:'CHAOEXアプリはまだありません',
  godown:'をダウンロード',
}

