export default {
  Mining_commune: '公社の鉱',
  Mining_commune_formally: '公社の採掘ラインを15億分割',
  Accumulated_distribution: '累積して配る',
  Distribution_of_yesterday: 'きのう配った',
  Block_finding_commune: '爆塊公社',
  commune: '公社',
  nodata:'一時データ',
  Not_available: 'ジャスミン',
  Rule_description: 'ルール説明',
  Rule_url: 'https://chaoex934.zendesk.com/hc/en-us/articles/360038181473-CHE-Mining-Commune-Rules-Specification',
  Coming_soon: 'ご期待ください',
  Mining_is_ongoing: '掘り進めている',
  Commune_leader_wanted: '公社管理募集中',
  Disbanded_Build_failed: '解散した',
  Build_commune: '公社を創設する',
  Current_commune_balance: '現在の公社資金',
  Mining_duration: '掘削時間:',
  Gains_of_yesterday: '昨日の収益',
  Commission: '手数料',
  Full_up: 'すでに満',
  Join: '加入',
  create: '確かめる',
  Failed: '失敗',
  Commune_name: '公社名',
  Commission: '手数料',
  Choose_a_symbol: '選択フラグ',
  Can_not_be_changed: '選択後、変更不可',
  Mining_automatically: '30日間の公社満(CHE)2000wは自動的に採掘を開始し,満でなければ自動的に解散する',
  Locked_quantity: 'ロック倉庫数',
  Currently_available: '現在のアカウントが',
  Transfer: '転がしに行く',
  create_commune: '共創公社',
  Participate_in_commune: '共創に参加する',
  Join_in_commune: '公社に加入する',
  Remaining_positions: '余剰管理ポジション',
  Last_modification_time: '前回の修正時点',
  Click_here_for_details: '詳細を調べる',
  days_left: '残した',
  The_commune_will: '未成公社は自主解散する',
  Notice:'注意:',
  Notice1:'1.公社が採掘を開始してから90日後に社長は解散の礎石を申請でき、31日後に自動的に解散し、解散期間を延長しても採掘収益と手数料をもらえる。',
  // Notice2:'2 .社長の権利が手数料を設置、範囲が−30%、72時間内に一回しか設置。',
  Notice3:'2.採掘の割合は公社の貨幣の総数量の増加に従って増加し、天井の数量は1日135万個である。',
  Notice4:'3.持ちコインが1千以上で、公社に加入して社員になることを申請することができ、1千の整数倍で加入することができる。加入当日に鉱掘収益を得ることができ、公社に加入してから30日後に自由に当該公社を脱退することができ、脱退申請後直ちに効力が発生し、脱退当日には収益がない。',
  Notice5:'4.ご褒美決済時間:収益を獲得した後、翌日午前1時以降に決済し、決済後の収益は自由になります。',
  

  Please_input_commune: '公社名を入力してください',
  Please_set_commission: '手数料を入力してください',
  commission_range_is: '手数料が0 ~ 30%の間になりますので、入力し直してください',
  Insufficient_available_balance: '現在利用できる残高は合計しないので,転がしてください',
  Please_open_your: '取引パスワードを開いてください',
  Trading_password: '取引パスワードの間違い',
  The_remaining_position : '残りのポジションが不足していますので、ロックボックスの数を入力し直してください',
  The_remaining_management: '残りの管理ポジションが不足していますので、ロックボックスの数を入力し直してください',
  The_lockups_number: 'ロックボックスの数が500w ~ 1999wの間になりますので、入力し直してください',
  Transfer_succeed: '回転成功',
  Please_enter_the_correct_amount:'正しい金額を入力してください',
  Transfer_failed: '引っ替えに失敗する',
  insufficient_transfereable_balance: '目下引換え可能残高が不足している',
  Creation_time: '創設時:',
  Disband: '解散',
  Range_in_hours: '0 ~ 30%の範囲で、次回は72時間後に設置します',
  characters_can_not_be_changed: '2-10文字、英数字対応、変更不可',
  Current_asset: '現在の公社資金',
  Commune_Rank: '現在の公社順位',
  participants: '人が参加',
  Remaining_postitions: '剰余倉位:',
  Block_finding_and_profits:'爆発と収益',
  Block_finding_and_profits1:'1)爆発塊:公社の中のCHEの数量が最初に2億の頭打ちの数量に達した最初の3つの公社、爆発塊公社であり、それぞれ2000万、1000万、500万のCHE貨幣を獲得することができる。',
  Block_finding_and_profits2:'2)収益分配:当該公社の全利用者は,当該公社の総CHEコイン数(2億)に占めるCHEの保有枚数の割合でバースト収益を割り当て,手数料を差し引いたものをバースト収益とする。管理チームはユーザーが支払う手数料を割合で獲得する。',
  Block_finding_and_profits3:'3)制限ルール:同一コミューンは1回のバーストチャンスしか獲得できず,同一ユーザが複数回のバーストに参加できる。',
  Block_finding_and_profits4:'4)インセンティブ決済時間:2億を満たした後、翌日午前1時以降に決済し、決済後の収益が自由になる。',
  Block_finding_and_profits5:'5)総収入1800万は掘り鉱の総量15億に含まれる。',

}

