export default {
  selectAdd:'選択されたトークンのアドレス',
  Adda:'+ 添加地址',
  kmd:'活動の詳細を知る…',
  copyText:'コピー',
  affirm:'確定',
  abolish:'キャンセル',
  geschw:'データは提供できません',
  Deposit:'充電',
  withdrawals:'やり取りするだけ',
  changeEx:'両替',
  proBack:'資産センター',
  title: 'チャージ&アブダクション',
  Title: 'チャージ記録',
  dw: '1日あたりの限度額を提示する',
  Balances: '既存資産のみを表示する',
  CapitalRecord:'資産流水記録',
  gu: '総資産換算',
  to: 'まで',
  all: 'すべて',
  withdraw: '引き出し記録',
  property: '資産センター',
  entrust: '当面の依頼',
  current: '歴史的依頼',
  deal: '成約の記録',
  unFinished: '未完成',
  finished: '完了した',
  transaction: '取引依頼記録',
  iu: '今日は既に限度額を引き上げた',
  searchCur:'貨为替を探索する',
  status: '状态',
  type: 'タイプを満たす',
  Deposits: '充',
  choice: '充電タイプを選択してください',
  noRecord: 'データ提供はまだできません!',
  Withdrawals: '提',
  pay: '充造幣',
  sell: '提造幣',
  Trade:'取引',
  much:'より',
  coin: '幣種',
  action: '操作',
  fullName: 'フルネーム',
  totalAsset: '総額',
  available: '可用',
  availabledown: '利用可能数',
  Assets: '既存資産',
  inOrder: '凍結',
  copy: '複製をクリックする',
  payAddress: 'チャージアドレス',
  last: 'チャージが完了すると、履歴ページの追跡に進みます。',
  text_1: '使用',
  text_2: 'アドレスチャージが必要です',
  text_3: '非',
  text_4: '資産は取り戻すことができない。',
  text_5: '禁止されている',
  text_6: 'アドレスの充填、除',
  text_7: 'その他の資産は、いかなるものでも充当する',
  text_8: 'アドレスの',
  text_9: '以上のネットで确认しなければ帳簿に届きません。',
  sellAddress: '現住所',
  Withdrawal: 'やり取りするだけ',
  sellText: '下記に今回の呼び出し先を入力してください',
  lable: '備考タグ',
  address: 'アドレス',
  amount: '数',
  max: 'すべて引き出します',
  tradePassword: 'トランザクション暗号',
  fees: '手数料',
  submit: '提出',
  willGet: '実際に帳簿に記入する',
  done: '引き出しが完了すれば、履歴ページの追跡に進みます',
  minCoin: '最小提牌数はである',
  notFound: '無',
  ivc: '画像検証コード',
  sv: '検証コードを取得する',
  sellTitle: '現住所',
  evc: 'メール検証コード',
  send: '送信',
  alert: 'KYC2認証を先に行ってください',
  success: 'テイクワン成功',
  fee: 'インターネット手数料',
  google: 'google検証',
  way: '検証方式',
  emil: 'メール',
  ph: '携帯電話',
  pvc: '携帯電話の検証コード',
  pd: '(ChaoExから他のプラットフォームへの転出時に必要)',
  tp: '未記入では入金できません!',
  pl: '選んでください',
  t_1: 'チャージステップ:',
  t_2: 'チャージアドレス',
  t_3: '(必ず記入してください)',
  t_4: '3.その他の情報を記入し、チャージを完了する',
  t_5: '1.記入',
  t_6: '2.記入',
  a: '全部',
  y: '既存資産',
  f: '硬貨',
  plp: '携帯電話をバインドしてください',
  plo: 'google認証と結びつけてください',
  ratio: '為替レート',
  ea: '両替数量',
  safe: '両替する',
  ec: '両替',
  lab1: 'その数を消費する',
  lab2: '資産、本人はリスクを知って、両替を確定する。',
  pld: '取引パスワードを入力してください',
  ppo: '取引パスワードを開いてください',
  apply: '申請',
  unlock: '解仓',
  ylnn: 'お宅の鍵倉ノード数',
  ChexTotal:'CHEXロック総量',
  plnn: 'プラットフォームはノード総量をロックする',
  ptlnn: '昨日のシングルノード収益',
  nm: 'ノード管理',
  node: 'ノード',
  annan: '数は空であってはならない',
  dpnn: '取引のパスワードは空であってはならない',
  applynumerror: '*数が間違っています。整数を入力してください',
  applyS: '申請ノードが成功し,ノードロック発生時刻が明日0時となる',
  lnnan: '解仓ノード数は空ではない',
  locknumerror: '*解倉ノードの数が間違っていますので,解倉ノードの整数を入力してください',
  giveupnode: '解倉後はロックの時間とノードの鉱収益を放棄して、解倉のノードを確認してくださいか?',
  nodeS: '解倉ノードが成功する',
  cnum: '利用可能数',
  sd: '初期収益日',
  ann: '申請ロック数(万)',
  anNumber: '申請ノード数',
  clocknum: '解倉ノード数',
  clocknums: '解倉ノード数',
  clocknumber: '解倉ノード数',
  locknum: 'ロックできるノード数',
  dp: 'トランザクション暗号',
  transfer: '記録を変える。',
  app: 'まずアプリの操作に行って、あなたの理解と支持に感謝します!',
  transferbtn: '划转',
  configinfo: '両替情報を確認する',
  changecode: '両替CODE数',
  changeusdt: 'USDT数を両替する',
  nowprice: 'リアルタイム価格',
  getusdt: 'USDT数を得る',
  getcode: '獲得CODE数',
  cancle: 'キャンセル',
  sureconfig: '確認',
  usdtsure: '両替価格はUSDTリアルタイム価格で両替し,本人はリスクを承知で両替を確定する',
  CHEXnodesmanagement: 'CHEXノード管理',
  rewardCenter:'資産特別区を奨励する',
  youtotal: '総収益',
  InRecord:'収益記録',
  youreven: '収益の分配を待つ',
  nodeList: 'ノードリスト',
  RevernueRecord: '収益記録',
  chexNode: '*10万CHEX=1ノード',
  applyNode: '申請錠倉',
  unlockNode: '解倉ノード',
  Nodes:'ノード',
  hintOne: '1.ノードロック時間は申請の日から翌日の00:00から有効である。',
  hinttwo: '2.連続して30日間施錠した後に収益を開始し、翌日の昼12:00に収益を出す。',
  hintScheme: 'チェックアウト案に同意してください',
  applyTime: '申し込み時間',
  applyNodeNum: '申請ノード数',
  lockNodeNum: '倉ノード数',
  earnings: '総収益(CHEX)',
  stayOut: '収益の分配を待つ',
  beginTime: '初期収益日',
  serNum: '番号',
  nodeStatus: 'ノード状態',
  lockPer: 'ロックアウト日数',
  totalChex: '総収益(CHEX)',
  lockTime: '解倉時間',
  locking: '键を仓',
  unlocking: '解倉',
  nodesure: '解倉申請が最も遅いノードを優先し,本人が承知して解倉を確認する',
  entrustRecord: '依頼記録',
  EarningsYesterday:` < p >ルールによって、昨日まで23:59:59鍵仓満30日間のノード同点昨日500,000 CHEX獎勵。單ノード利得計算公式=500,000 CHEX / 滿足條件的節點數。</p>`,
  revenue:'節點收益',
  minTranferIn:'最小転入数は',
  minTranferOut:'最小転出数は',
  doneTranfer: '転記が完了すると、履歴ページの追跡に進みます',
  epayTran:'Epayの転記',
  epayTranUUEX:'UUEX',
  tranIn:'転入',
  tranOut:'転出',
  sureIn:'転入確認',
  sureOut:'転出確認',
  doneTranferIn:'移行完了後、履歴ページ追跡に移行します',
  doneTranferOut:'転出完了後、履歴ページ追跡に移行することができます',
  gotoEpay:'支払いはEpay公式サイトに行ってください',
  go:'すぐに行く',
  aTime:'申し込み時間',
  epayType:'タイプ',
  outAccount:'Epayアカウントを受け取ります',
  account:'Epayアカウント',
  n:'备考',
  formatError:'Epayアカウントのフォーマットが間違っています',
  pinputEpay:'Epayアカウントを入力してください',
  addaccount:'Epayアカウントを追加します',
  epayFormatErr:'Epayアカウントのフォーマットが間違っています',
  addsu:'Epayアカウント追加成功',
  tranoutsu:'転出成功',
  epayRecord:'Epayレコード',
  epin:'Epay転入',
  epout:'Epay転出',
  numerr:'数量入力ミス',
  plerr:'Epayアカウントを入力してください',
  noopenepay:'Epayアカウントは未開設',
  goregiepay:'登録に行く',
  aword:'資産特別区を奨励する',
  applyL1:'1、歩合:自然日数で計算して、鍵倉の期日当日を含み、期日当日を含まない。',
  applyL2:'2、解倉発行収益:期日当日の14:00ちょうど、プラットフォームはユーザーの元金と収益を自動的にユーザーアカウントに発行する。',
  wenxirule:'すべてCHAOEXにCHEXを持っていて、半年の鎖倉を利用して10%の年化収益を享受することができます;鎖倉1年、年化収益12%、満期後に元利金を同時に支払うことができる。錠倉数:毎回錠倉が10万CHEXを下回らないで、錠倉数を増やすことができて、超過部分は1万の整数倍になる',
  shanrule:'1. CHAOEXの保有資産の総資産値が300 USDT以下のユーザーは、毎日年化収益6%のインセンティブを受け、CHEXに換算して個人アカウントに発行できる。毎日24:00にユーザーの保有資産数をスナップショットし、当時の市場価格で計算する。満足の条件のユーザーは毎日年化収益の6%のインセンティブを楽しむ2 .発时间:3 .毎日24:00で両替usdt価格:chaoex 24:00で毎日の市场价どおり喜ばしい採算4 .両替chex価格:通りchex毎日平均価格=当日chex取引金額/当日chexされ数5 .統計範囲はユーザーに計上可用資産と注文奨励範囲、鍵を仓資産計上奨励しない範囲',
  paydrowMes:`<p>2019年1月31日前，完成KYC 2级认证，</p>
  <p>可获得1 USDT奖励完成KYC </p>
  <p>3级认证，可获得2 USDT奖励。</p>`,
  awardDtail:'奨励明細',
  awardProperty:'総資産を奨励する',
  shan:'閃息宝',
  shanRecord:'収益記録',
  shan1:'累積収益(CHEX)',
  shan2:'昨日の資産(USDT)',
  shan3:'昨日の収益(CHEX)',
  shan4:'両替CHEX価格(USDT)',
  shanBtn:'受給',
  wenCal:'ロックバック収益=すでに獲得した収益+予想収益',
  alGet:'受領済み',
  wen:'安定した宝。',
  wenRecord:'鍵倉記録',
  wen1:'総収益(CHEX)',
  wen2:'既に収益を上げている(CHEX)',
  wen3:'予想収益(CHEX)',
  wenBtn:'申請錠倉',
  lishi:'歴史的活動',
  lishi1:'ノード管理',
  lishi2:'お宅の鍵倉ノード数',
  lishi3:'CHEXロック総数',
  lishi4:'総収益(CHEX)',
  lishi5:'待発収益(CHEX)',
  lishiRecord:'収益記録',
  more:'ノードレコード',
  minLock:'最低10万CHEX',
  lockPerid:'ロックサイクル',
  month1:'月',
  intrate:'年利率',
  roi:'予想収益:',
  sure:'確定',
  not300:'200USDT未満',
  minnum:'数は10以下ではない',
  pstp:'取引パスワードを設定してください',
  XLMCOIN:'現在のところ、アドレスタグがMEMO_TEXTであるもののみがサポートされているが、他のタイプのアドレスタグには対応していない。XLM充貨はpayment取引タイプのみをサポートし、その他任意の取引タイプ(pathpaymentなど)は充貨できないことをご了承ください。',
  step1:'第一歩',
  s1:'GRINを上のアドレスに振り替えてください。',
  step2:'ステップ2',
  s2:'振替情報に基づき、振替注文を記入する。',
  step3:'ステップ3',
  s3:'完了する。',
  endInfo:'プラットフォームは入金確認後に充てん記録を表示する。',
  txidplh:'提幣ハッシュ値を記入してください',
  amountplh:'充てん数',
  nodedetail:'奨励明細',
  auctionRecord:'オークション勝利記録',
  info_modal_title:'尊敬するユーザー、',
  info_modal_content:'口座の資金リスクを低減し、あなたの資産の安全を保証するため、CHAOEXプラットフォームは現在、提幣サービスを人工審査処理に変更します。私たちは申し込みの提出時間順に、ユーザーの引き出しの需要に対して一つ一つ処理して、お待ちください。',
  Tran:'划转',

  mingmgr:'公社の鉱山管理',
  cashmount: '鉱床口座は残高が利用できる',
  allproperty: '総資産',
  gotrans: '転がしに行く',
  gomining: '鉱を掘る',
  miningclubfrzen: '鉱山公社凍結',
  yesProfit: '昨日の収益',
  yesProfitrate: '昨日の収益率',
  cumulate : '累積収益',
  clubmgr: '公社名',
  clubStatus: '公社状態',
  inmining: '鉱に',
  inenjoy: '募集中',
  dismissed: '解散した',
  miningtime: '鉱掘り時間',
  rank: 'ランキング',
  currentawardpool: '現在の公社の資金プール',
  bemgr: '管理として投入する',
  beclubor: '社員として投入する',
  cumulateinvest: '積算投入',
  cumulateProfit: '累積収益',
  profitrate: '利回り',
  yesAllprofit: 'きのうの総収益',
  awardprofit: 'プレミアム報酬',
  operation: '操作',
  cashrecord: '資金の流れ。',
  setfee: '設置手数料',
  currentfee: '現在の手数料',
  inputnum: '回転数を入力してください',
  nextfor72h: '0 ~ 30%の範囲で、次回は72時間後に設置します',
  currentLockamount: '現在の公社の金庫の金額',
  cangoutamount: '脱退可能額',
  lockover30: '穴を掘って30日以内に社員の資金を脱退できる',
  lookinverstdetail: '投入明細を見る',
  sureafterprofit: '確認後,立即生效,退出當日無收益',
  outclub: '当面の公社から脱退する',
  discurrentclub: '現在の公社を解散する',
  clubminingtime: '鉱掘りの時間を取る',
  applydisstime: '解散時期',
  scope30: '範囲は0−30%である',
  disband: '解散',
  join: '加入',
  Exit: '退出',
  feeprofit: '手数料収益',
  awardpro: 'TOP報酬',
  boomawardpro: 'バーストは報酬を与える',
  cluballprofit: '公社総収益',
  clubperson: '公社の人数',
  lastsetfeetime: '最後に1回手数料時間を設定する',
  clubcreatetime: '公社設立時',
  clubdistime: '公社解散時点',

  transRecord: '記録を変える。',
  incomRecord: '収益記録',
  inputRecord: '投入記録',
  miningprof: '採掘収益',
  poverincom: '昨日の収益率=昨日の総収益/昨日の掘削中のロックアウト数*100%',
  povermgr1: '累積総収益/収益率:未開発公社無この収益収益率=現在の公社累積総収益/現在の公社累積投入*100%',
  povermgr2: '昨日の総収益率:昨日の未鉱公社の収益率=現在の公社の昨日の総収益率/現在の公社の昨日までの累積投入*100%',
  povermgr3: '手数料:公社社長は72時間以内に1回だけ調整できるようにすることができる',
  povermgr4: '特別報酬報酬:手数料報酬(社員として投入してもこの報酬はない)、バースト報酬報酬、トップ報酬報酬を含む',
  povermgr5: '状態:鉱掘り中、募集中、創建失敗、解散し、鉱掘り中の公社のみが収益を発生する',
  povermgr6: '以下の利得計算はいずれも個人利得である',
  Exchangebalances: '通貨口座',
  Miningbalances: '採掘口座',
  notfee: '振り替えに手数料は必要ありません',
  cannotundo: 'この操作は破棄できない',

}
