export default {
  selectAdd:'選擇的提幣地址',
  Adda:'+ 添加地址',
  kmd:'瞭解活動詳情...',
  copyText:'複製',
  affirm:'確定',
  abolish:'取消',
  geschw:'暫無可提供數據',
  Deposit:'充值',
  withdrawals:'提現',
  changeEx:'兌換',
  proBack:'資產中心',
  title: '充值 & 提現',
  Title: '充值記錄',
  dw: '每日提幣限額',
  Balances: '僅顯示已有資產',
  CapitalRecord:'資产流水記錄',
  gu: '總資產折合',
  to: '至',
  all: '全部',
  withdraw: '提現記錄',
  property: '資產中心',
  entrust: '当前委托',
  current: '歷史委托',
  deal: '成交记录',
  unFinished: '未完成',
  finished: '已完成',
  transaction: '交易委託記錄',
  iu: '今日已用提幣額度',
  searchCur:'搜索幣種',
  status: '狀態',
  type: '充/提类型',
  Deposits: '充',
  choice: '请选择充提类型',
  noRecord: '暫無可提供數據!',
  Withdrawals: '提',
  pay: '充幣',
  sell: '提幣',
  Trade:'交易',
  much:'更多',
  coin: '幣種',
  action: '操作',
  fullName: '全稱',
  totalAsset: '總額',
  available: '可用',
  availabledown: '可用数量',
  Assets: '已有资产',
  inOrder: '凍結',
  copy: '點擊複製',
  payAddress: '充值地址',
  last: '充值完成後，妳可以進入歷史記錄頁面跟蹤進度。',
  text_1: '使用',
  text_2: '地址充值需要',
  text_3: '非',
  text_4: '資產將不可找回。',
  text_5: '禁止向',
  text_6: '地址充值，除',
  text_7: '之外的資產，任何充入',
  text_8: '地址的',
  text_9: '個以上網絡確認才能到賬。',
  sellAddress: '提現地址',
  Withdrawal: '提現',
  sellText: '請在下方輸入本次提現地址',
  lable: '備註標簽',
  address: '地址',
  amount: '數量',
  max: '全部提現',
  tradePassword: '交易密碼',
  fees: '手續費',
  submit: '提交',
  willGet: '實際到賬',
  done: '提現完成後，妳可以進入歷史記錄頁面跟蹤進度',
  minCoin: '最小提幣數量為',
  notFound: '無',
  ivc: '圖片驗證碼',
  sv: '獲取驗證碼',
  sellTitle: '提现地址',
  evc: '郵箱驗證碼',
  send: '發送',
  alert: '請先進行KYC2認證',
  success: '提幣成功',
  fee: '網絡手續費',
  google: '谷歌驗證',
  way: '驗證方式',
  emil: '郵箱',
  ph: '手機',
  pvc: '手機驗證碼',
  pd: '(從ChaoEx轉出至其他平臺時需要)',
  tp: '(未填寫將無法到賬！)',
  pl: '請選擇',
  t_1: '充值步驟：',
  t_2: '充值地址',
  t_3: '(請務必填寫)',
  t_4: '3.填寫其他信息，完成充值',
  t_5: '1.填寫',
  t_6: '2.填寫',
  a: '全部',
  y: '已有資產',
  f: '分叉幣',
  plp: '請綁定手機',
  plo: '請綁定谷歌認證',
  ratio: '兌換比例',
  ea: '兌換數量',
  safe: '安網幣兌換',
  ec: '兌換',
  lab1: '將消耗相應數量',
  lab2: '資產，本人已知風險，確定兌換。',
  pld: '請輸入交易密碼',
  ppo: '請開啟交易密碼',
  apply: '申請',
  unlock: '解倉',
  ylnn: '您的鎖倉節點數',
  ChexTotal:'CHEX鎖倉總量',
  plnn: '平台鎖倉節點總量',
  ptlnn: '昨日單節點收益',
  nm: '節點管理',
  node: '節點',
  annan: '數量不可為空',
  dpnn: '交易密碼不可為空',
  applynumerror: '*數量錯誤，請輸入整數',
  applyS: '申請節點成功，節點鎖倉生效時間為明日0時',
  lnnan: '解倉節點數量不可為空',
  locknumerror: '*解倉節點數量錯誤，請輸入可解倉節點的整數',
  giveupnode: '解倉後將放棄鎖倉時間和節點挖礦收益，請確認是否解倉節點？',
  nodeS: '解倉節點成功',
  cnum: '可用數量',
  sd: '初始收益日期',
  ann: '申請鎖倉數量(萬)',
  anNumber: '申請節點數',
  clocknum: '可解倉節點數量',
  clocknums: '解倉節點數量',
  clocknumber: '解倉節點數',
  locknum: '可鎖倉節點數',
  dp: '交易密碼',
  transfer: '劃轉紀錄',
  app: '請您先去APP操作，感謝您的理解與支持！',
  transferbtn: '劃轉',
  configinfo: '確認兌換信息',
  changecode: '兌換CODE數量',
  changeusdt: '兌換USDT數量',
  nowprice: '實時兌換價格',
  getusdt: '獲得USDT數量',
  getcode: '獲得CODE數量',
  cancle: '取消',
  sureconfig: '確認',
  usdtsure: '兌換價格根據USDT實時價格進行兌換，本人已知曉風險，確定兌換',
  CHEXnodesmanagement: 'CHEX節點管理',
  rewardCenter:'獎勵資產專區',
  youtotal: '總收益',
  InRecord:'收益記錄',
  youreven: '待發放收益',
  nodeList: '節點列表',
  RevernueRecord: '收益紀錄',
  chexNode: '*10萬CHEX=1節點',
  applyNode: '申請鎖倉',
  unlockNode: '解倉節點',
  Nodes:'節點',
  hintOne: '1.節點鎖倉時間自申請之日起第二天的00:00開始生效。',
  hinttwo: '2.連續鎖倉30天後開始收益，收益將在第二天中午12:00發放。',
  hintScheme: '請同意並勾選解倉方案 ',
  applyTime: '申請時間',
  applyNodeNum: '申請節點數',
  lockNodeNum: '鎖倉節點數',
  earnings: '總收益（CHEX）',
  stayOut: '待發放收益',
  beginTime: '初始收益日期',
  serNum: '序號',
  nodeStatus: '節點狀態',
  lockPer: '鎖倉天數',
  totalChex: '總收益（CHEX）',
  lockTime: '解倉時間',
  locking: '鎖倉',
  unlocking: '解倉',
  nodesure: '將優先解倉申請時間最晚的節點，本人知曉，確認解倉',
  entrustRecord: '委托记录',
  EarningsYesterday: `<p>根据规则，截止至昨日23:59:59連續鎖倉滿30天的節點平分昨日500,000 CHEX獎勵。單節點收益計算公式=500,000 CHEX / 滿足條件的節點數。</p>`,
  revenue:'節點收益',
  minTranferIn:'最小轉入數量為',
  minTranferOut:'最小轉出數量為',
  doneTranfer: '劃轉完成後，妳可以進入歷史記錄頁面跟蹤進度',
  epayTran:'Epay劃轉',
  epayTranUUEX:'UUEX劃轉',
  tranIn:'轉入',
  tranOut:'轉出',
  sureIn:'確認轉入',
  sureOut:'確認轉出',
  doneTranferIn:'轉入完成後，您可進入歷史記錄頁面跟蹤進度',
  doneTranferOut:'轉出完成後，您可進入歷史記錄頁面跟蹤進度',
  gotoEpay:'請前往Epay官網進行支付操作',
  go:'立即前往',
  aTime:'申請時間',
  epayType:'類型',
  outAccount:'收款Epay賬號',
  account:'Epay賬號',
  n:'備註',
  formatError:'Epay賬號格式錯誤',
  pinputEpay:'請輸入Epay賬號',
  addaccount:'添加Epay賬號',
  epayFormatErr:'Epay賬號格式錯誤',
  addsu:'添加Epay賬號成功',
  tranoutsu:'轉出成功',
  epayRecord:'Epay記錄',
  epin:'Epay 轉入',
  epout:'Epay 轉出',
  numerr:'數量輸入錯誤',
  plerr:'請輸入Epay賬號',
  noopenepay:'未開通Epay帳戶',
  goregiepay:'去註冊',
  aword:'獎勵資產專區',
  applyL1:'1、計息：按照自然天數計算，包括鎖倉日期當日，不包括到期日期當日。',
  applyL2:'2、解倉發放收益：到期日期當日的14:00整，平臺將用戶的本金和收益自動發放至用戶帳戶。',
  wenxirule:'凡在CHAOEX持有CHEX，鎖倉半年可享受年化收益10%；鎖倉1年，可享受年化收益12%，期滿後同時支付本息和。鎖倉數量：每次鎖倉不低於十萬CHEX，可增加鎖倉數額，超出部分為1萬的整數倍即可',
  shanrule:'1.凡在CHAOEX持倉總資產等值不少於300 USDT的用戶，每日可享受年化收益6%獎勵並折算成CHEX發放至個人帳戶。每日24:00對用戶持倉資產數量進行快照並按照當時的市場價進行核算。滿足條件的用戶將每日享受年化收益6%的獎勵   2.快照時間：每日24:00   3.兌換USDT價格：按照CHAOEX每日24:00的市場價進行等值核算   4.兌換CHEX價格：按照CHEX每日均價=當日CHEX成交總金額/當日CHEX成交總數    5.統計範圍：用戶持可用資產和掛單資產計入獎勵範圍，鎖倉資產不計入獎勵範圍',
  paydrowMes:`<p>2019年1月31日前，完成KYC 2级认证，</p>
  <p>可获得1 USDT奖励完成KYC </p>
  <p>3级认证，可获得2 USDT奖励。</p>`,
  awardDtail:'獎勵明細',
  awardProperty:'獎勵總資產',
  shan:'閃息寶',
  shanRecord:'收益記錄',
  shan1:'累計收益(CHEX）',
  shan2:'昨日資產(USDT) ',
  shan3:'昨日收益(CHEX）',
  shan4:'兌換CHEX價格(USDT)',
  shanBtn:'領取',
  wenCal:'鎖倉收益=已獲收益+預計收益',
  alGet:'已領取',
  wen:'穩息寶',
  wenRecord:'鎖倉記錄',
  wen1:'總收益(CHEX)',
  wen2:'已獲收益(CHEX) ',
  wen3:'預計收益(CHEX) ',
  wenBtn:'申請鎖倉',
  lishi:'歷史活動',
  lishi1:'節點管理',
  lishi2:'您的鎖倉節點數',
  lishi3:'CHEX鎖倉總數',
  lishi4:'總收益（CHEX）',
  lishi5:'待發放收益（CHEX）',
  lishiRecord:'收益記錄',
  more:'節點記錄',
  minLock:'最少鎖倉10萬CHEX',
  lockPerid:'鎖倉週期',
  month1:'月',
  intrate:'年利率',
  roi:'預計收益: ',
  sure:'確定',
  not300:'不足200USDT',
  minnum:'數量不能小於10',
  pstp:'請先設置交易密碼',
  XLMCOIN:'目前僅支持地址標籤為MEMO_TEXT的充幣，其他類型的地址標籤不可充幣。XLM充幣僅支持payment交易類型，任何其他交易類型（如pathpayment）不可充幣，請您諒解。',
  step1:'第一步',
  s1:'請將GRIN轉賬到上方地址。',
  step2:'第二步',
  s2:'根據轉帳信息，填寫轉賬訂單。',
  step3:'第三步',
  s3:'完成。',
  endInfo:'平台確認到賬後將會顯示充幣記錄。',
  txidplh:'請填寫提幣哈希值',
  amountplh:'充幣數量',
  nodedetail:'奖励明细',
  auctionRecord:'Auction獲勝記錄',
  info_modal_title:'尊敬的用戶，',
  info_modal_content:'為降低賬戶資金風險，保證您的資產安全，CHAOEX平台現階段提幣服務暫改為人工審核處理。我們將按提交申請的時間順序，對用戶的提幣需求進行逐一處理，請您耐心等候。',
  Tran:'劃轉',

  mingmgr:'公社挖礦管理',
  cashmount: '挖礦賬戶可用餘額',
  allproperty: '總資產',
  gotrans: '去劃轉',
  gomining: '去挖礦',
  miningclubfrzen: '挖礦公社凍結',
  yesProfit: '昨日收益',
  yesProfitrate: '昨日收益率',
  cumulate : '累計收益',
  clubmgr: '公社名稱',
  clubStatus: '公社狀態',
  inmining: '挖礦中',
  inenjoy: '招募中',
  dismissed: '已解散',
  miningtime: '挖礦時間',
  rank: '排名',
  currentawardpool: '當前公社資金池',
  bemgr: '作為管理投入',
  beclubor: '作為社員投入',
  cumulateinvest: '累計投入',
  cumulateProfit: '累計收益',
  profitrate: '收益率',
  yesAllprofit: '昨日總收益',
  awardprofit: '額外獎勵收益',
  operation: '操作',
  cashrecord: '資金流水',
  setfee: '設置手續費',
  currentfee: '當前手續費',
  inputnum: '請輸入劃轉數量',
  nextfor72h: '範圍在0-30%，下次設置72小時後',
  currentLockamount: '當前公社鎖倉金額',
  cangoutamount: '可退出金額',
  lockover30: '挖礦鎖倉滿30天后可退出社员资金',
  lookinverstdetail: '查看投入明細',
  sureafterprofit: '確認後,立即生效,退出當日無收益',
  outclub: '退出當前公社',
  discurrentclub: '解散當前公社',
  clubminingtime: '公社挖礦時間',
  applydisstime: '申請後解散時間',
  scope30: '範圍在0-30%',
  disband: '解散',
  join: '加入',
  Exit: '退出',
  feeprofit: '手續費收益',
  awardpro: 'TOP獎勵收益',
  boomawardpro: '爆塊獎勵收益',
  cluballprofit: '公社總收益',
  clubperson: '公社人數',
  lastsetfeetime: '最後壹次設置手續費時間',
  clubcreatetime: '公社創建時間',
  clubdistime: '公社解散時間',

  transRecord: '劃轉記錄',
  incomRecord: '收益記錄',
  inputRecord: '投入記錄',
  miningprof: '挖礦收益',
  poverincom: '昨日收益率=昨日總收益/昨日挖礦中鎖倉數量*100%',
  povermgr1: '累計總收益/收益率：未挖礦公社無此收益    收益率=當前公社累計總收益/當前公社累計投入*100%',
  povermgr2: '昨日總收益/收益率：昨日未挖礦公社無此收益    收益率=當前公社昨日總收益/當前公社截止到昨日累計投入*100%',
  povermgr3: '手續費：公社社長有權設置   72小時內僅能調整一次',
  povermgr4: '格外獎勵收益：包含手續費收益（作為社員投入無此收益）、爆塊獎勵收益、TOP獎勵收益',
  povermgr5: '狀態：挖礦中、招募中、創建失敗、已解散，其中僅挖礦中的公社產生收益',
  povermgr6: '以下收益計算均為個人收益',
  Exchangebalances: '幣幣賬戶',
  Miningbalances: '挖礦賬戶',
  notfee: '劃轉不需要手續費',
  cannotundo: '此操作無法撤消',

}
