export default {
  rekhw:'データ提供はまだできません!',
  searchCur:'金銭種を選択する',
  title: 'チャージ記録',
  date: '選択时间',
  allCoin:'すべて',
  to: 'まで',
  coin: '为替',
  status: '型を選ぶ',
  typeC:'タイプ',
  finished: '完了した',
  unFinished: '未完成',
  noRecord: 'データは提供できません',
  time: '時間',
  address: 'アドレス',
  amount: '数',
  fees: '手数料',
  willGet: '実際に帳簿に記入する',
  all: 'すべて',
  issueDate: '発行日時',
  IssuingState: '報酬放出状態',
  nodeRevenue: 'シングルノード利得(CHEX)',
  number: '数',
  TotalRevenue: '総収益(CHEX)',
  locking: '键を仓',
  unlocking: 'ロック',
  distributed: '配布済み',
  ndistributed: '未発行',
  success: '成功',
  fail: '失敗',
  startTime:'開始時間',
  endTime:'終了時間',
  faT:'時間を配る',
  awardn:'奨励名',
  awardc:'金銭種を奨励する',
  awarda:'ご褒美数',
  ass:'アセット(USDT)',
  int:'利子(CHEX)',
  sta:'状态',
  lockTime:'ロック・タイム',
  lockedNum:'チャック数(CHEX)',
  lockedpe:'ロックサイクル',
  lockRate:'年利率',
  lockExpress:'満期時間。',
  notget:'受け取り不可',
  hodlget:'未受領',
  aleayget:'受領済み',
  roi:'収益(CHEX)',
  alis:'鎖倉に',
  unis:'もう終わった',
  month1:'ヶ月',

  Transferinto: '転入',
  Transferout: '転出',
  Transferintofor: '硬貨口座から転入する',
  Transferoutfor: '硬貨口座に転出する',
  operationtime: '作業時間',
  Transfermethod: 'タイプを変える',
  Amount: '金額',
  Operationtype: '操作型',
  increat: '作成中',
  inmining: '鉱に',
  inUnlock: 'ロックホールを解除する',
  details: '详细',
  clubstatus: '公社状態',
  cashSatus: '資金の詳細',
  sequ: 'りゅうすい号',
  Locktime: 'ロック・タイム',
  unLocktime: '解倉時間',
  unLocktimeType: '解倉タイプ',
  disbandStatus1: 'ユーザーが脱退を申請する',
  disbandStatus2: '社長解散',
  disbandStatus3: '掘削終了解倉',

  jionAndCom: '共創に参加する',
  buildCom: '公社を創設する',
  jionCom: '公社に加入する',
  propertyStatus: '資金状態',
}
