export default {
  UPA:'権限認証を知る',
  Reviewing:'審査中',
  nV: '未認証',
  v: '認証済み',
  lg: '最後のログイン',
  sD: '身分認証を完了する',
  dw: '[オピニオン]日貨の限度額',
  hw: 'より低いレーティングとより高い引き上げ限度が適用される',
  cu: '私たちに連絡する',
  svd: '身分認証を完了する',
  msg: 'パスワードやメール、googleの検証コードを誰にも公開しないでください。',
  tA: '総資産',
  aR: '資産記録',
  d: '充電',
  deal: 'チャージ、取引ができる',
  haveComplate: '認証済み',
  haveComplatePerson: 'ビデオ認証済み',
  kyc1: 'KYC.2の認証を完了してください',
  ylnn: 'お宅の鍵倉ノード数',
  plnn: 'プラットフォームはノード総数をロックする',
  ptlnn: 'プラットフォームは今日のシングルノード収益',
  nm: 'ノード管理',
  node: 'ノード',
  account: '口座',
  safe: '安全',
  invite: '招待する',
  fee_1: '取引手数料0.1%',
  fee_2: '取引手数料0.075%',
  fee_3: '取引手数料は0.05%',
  base: '基礎認証',
  person: '身分認証',
  video: 'ビデオ認証',
  goto: '認証',
  gu: '総資産換算',
  successful: '成功の誘い',
  code: '私の招待コード',
  inviteFriend: '友人を下男に誘う',
  inviteMoney:'登録を招き、気軽に下男に返す',
  loginRecord: '登録記録',
  securityRecord: '安全設置記録',
  revenueRecord: '収益記録',
  userMes:`<p>2019年1月31日までにKYCの2段階認証を完了し、</p>
  <p>1 USDTはKYCの完了を奨励する</p>
  <p>3レベル認証で、2 USDTボーナスがもらえる。</p>`,
  chexFee:'CHEXを使って取引手数料を差し引く',
  abolish:'キャンセル',
}
