export default {
    confirmSub:'確定',
    PerCen:'個人中心',
    DownApp:'1.下載安裝APP',
    sQc:'2.掃描二維碼',
    BK:'3.備份密鑰',
    OpenG:'4.開啟谷歌驗證',
    HaveApp:'我已安裝好APP',
    HaveQR:'我已完成二維碼掃描',
    HaveKey:'我已經記下了16位密鑰',
    Next:'下一步',
    CloseGA: '關閉谷歌驗證',
    login: '登錄密碼',
    gaCode: '谷歌驗證碼',
    submit: '解绑',
    bindGA: '綁定谷歌驗證',
    download: '下載安裝谷歌驗證器APP',
    clickDownload: '點此下載',
    scanCode: '使用谷歌驗證器APP掃描下方二維碼',
    secretKey: '密鑰',
    enterPassword: '請將16位密鑰準確記錄在紙上，並妥善保管，若手機丟失，您可以通過該密鑰恢復谷歌驗證',
    enterCode: '谷歌驗證碼',
    modalText: '為了您的賬號安全，我們強烈建議您開啓二次驗證。',
    modalText1: '請選擇您希望的二次驗證方式',
    iKnow: '我已知曉風險，',
    noSet: '暫不設置',
    bindMess: '如果您無法掃描二維碼，可將密鑰手動輸入到谷歌驗證APP中',
    bindMess1: '或輸入密鑰',
    tips: '溫馨提示',
    bindPhone:'綁定手機',
    bg:'手機號碼已綁定',
    bag:'谷歌認證已綁定',
    guAuthPwd:'請填寫登錄密碼',
    guAuthCode:'請填寫谷歌驗證碼',
    next:'下一步',
    nostrum:'通过人工客服重置您的谷歌验证需提交工单，可能需要至少7天时间来处理',
    way:'驗證方式',
    Vemail:'郵箱驗證',
    VSMS:'手機驗證',
    AVC:'獲取驗證碼',
    pl:'請選擇',
    errorMsg:'驗證碼有誤',
    dts:'拖動一下',
    dtr:'向右拖動',
    uf:'加載失敗',
    uld:'加載中',
    civ:'CHAOEX無感驗證',
    ck:'智能檢測中',
    vs:'驗證成功',
    vf:'驗證失敗',
    vip:'驗證中',
    mnn:'郵箱不能為空',
    pnn:'手機不能為空',
    send:'發送',
    successGa:'谷歌驗證開啟成功，將在3s後返回“個人中心”',
    errorGa:'谷歌驗證開啟失敗，將在3s後返回“個人中心”',
    successClose:'谷歌驗證關閉成功，將在3s後返回“個人中心”',
    errorClose:'谷歌驗證關閉失敗，將在3s後返回“個人中心”',
    sv:'獲取驗證碼',
}