export default {
    tc: '交易中心',
    h: '首頁',
    lg: '登錄',
    rg: '註冊',
    fd: '資產管理',
    dw: '充值&提現',
    dh: '充值記錄',
    wh: '提現記錄',
    th: '交易記錄',
    pi: '個人',
    od: '委託',
    ns: '幫助',
    Mining_commune: '公社挖礦',
    center:'支持中心',
    ac: '個人中心',
    lgt: '退出',
    ss: '安全設置',
    vd: '實名認證',
    logout: '退出成功',
    announcement:'公告',
    invite:'邀請好友',
    aboutCode: '關於CODE' ,
    gawt:'交易委託記錄',
    app:'請您先去APP操作，感謝您的理解與支持！',
    s:'設置',
    theme:'主題',
  black:'黑色',
  white:'白色',
  cur:'法幣切換',
  submit: '確認',
  getsuccessed:'領取成功',
    discount:'折扣申購',
    newCoin:'打新區',
    bbwd:'折申購BTC活動',
    endtime:'本次活動結束時間',
    day:'天 ',
    alq:'可用於鎖定:',
    afpq:'可用於申購: ',
    number:'數量',
    lockedn:'本次鎖定數量',
    lock:'鎖定',
    pci:'本次申購幣種信息',
    token:'代幣名稱',
    cl:'發行量/流通量',
    apq:'可申購數量',
    ql:'數量/簽',
    pp:'申購價/枚',
    op:'開盤價/枚',
    mwl:'單賬戶最大中籤數量',
    petnop:'請輸入申購數量',
    purchase:'申購',
    mpr:'我的申購記錄',
    data:'申購日期',
    spl:'成功申購簽數',
    ta:'總金額',
    ad:'活動細則',
    ls:'鎖定成功',
    ps:'申購成功',
    st:'現貨交易',
    iusertotal:'邀請有效用戶總數量',
    usdtPur:'USDT申購',
  chexPur:'CHEX申購',
  CHEX_Loan:'chex借貸',
  Follow:'社群',
  Support:'工單',
  Locked_assets_revenue:'穩息寶',
  Assets_revenue:'閃息寶',
  Fiat_Convert:'法幣交易',
  Financial_Center:'理財中心',
  alert: '請先進行KYC2認證',
  PleaseLogin:'請先登錄',
  PleasePhone:'請先綁定手機號',
  imgUrl:'https://coinmarketcap.com/zh/exchanges/chaoex/',
  whitepaper:'白皮書',
}
