export default {
    Rere:'邀請記錄',
    ERP:'專屬邀請海報',
    MyP:'我的專屬海報',
    MyId:'我的專屬ID',
    MyLink:'我的專屬鏈接',
    Copy:'複製',
    people:'人',
    copy:'復制',
    successful:'已成功邀請',
    way:'邀請方式',
    a:'邀請方式壹：復制您的鏈接推薦給您的好友',
    b:'邀請方式二：復制您的邀請碼給您的好友',
    c:'邀請方式三：邀請二維碼',
    link:'專屬鏈接',
    code:'專屬邀請碼',
    invite:'邀請好友',
    copyed:'復制成功',
    ylnn:'您的鎖倉節點數',
    plnn:'平台鎖倉節點總數',
    ptlnn:'平台今日單節點收益',
    nm:'節點管理',
    node:'節點',
    download:'下載到桌面',
    pap:'挑選海報 下載發送給好友',
}
