export default {
  rekhw:'暫無可提供數據！',
  searchCur:'选择幣種',
  title: '充值記錄',
  date: '選擇時間',
  allCoin:'全部',
  to: '至',
  coin: '幣種',
  status: '選擇類型',
  typeC:'類型',
  finished: '已完成',
  unFinished: '未完成',
  noRecord: '暫無可提供數據',
  time: '時間',
  address: '地址',
  amount: '數量',
  fees: '手續費',
  willGet: '實際到賬',
  all: '全部',
  issueDate: '發放日期',
  IssuingState: '收益發放狀態',
  nodeRevenue: '單節點收益（CHEX）',
  number: '數量',
  TotalRevenue: '總收益（CHEX）',
  locking: '鎖倉',
  unlocking: '解鎖',
  distributed: '已發放',
  ndistributed: '未發放',
  success: '成功',
  fail: '失败',
  startTime:'起始時間',
  endTime:'結束時間',
  faT:'發放時間',
  awardn:'獎勵名稱',
  awardc:'獎勵幣種',
  awarda:'獎勵數量',
  ass:'資產（USDT）',
  int:'利息（CHEX）',
  sta:'狀態',
  lockTime:'鎖倉時間',
  lockedNum:'鎖倉數量(CHEX)',
  lockedpe:'鎖倉週期',
  lockRate:'年利率',
  lockExpress:'到期時間',
  notget:'不可領取',
  hodlget:'未領取',
  aleayget:'已領取',
  roi:'收益（CHEX）',
  alis:'鎖倉中',
  unis:'已結清',
  month1:'个月',

  Transferinto: '轉入',
  Transferout: '轉出',
  Transferintofor: '從幣幣賬戶轉入',
  Transferoutfor: '轉出至幣幣賬戶',
  operationtime: '操作時間',
  Transfermethod: '劃轉類型',
  Amount: '金額',
  Operationtype: '操作類型',
  increat: '创建中',
  inmining: '挖矿中',
  inUnlock: '解除锁仓',
  details: '詳情',
  clubstatus: '公社狀態',
  cashSatus: '資金詳情',
  sequ: '流水號',
  Locktime: '鎖倉時間',
  unLocktime: '解倉時間',
  unLocktimeType: '解倉類型',
  disbandStatus1: '用戶申請退出',
  disbandStatus2: '社長解散',
  disbandStatus3: '挖礦結束解倉',

  jionAndCom: '參與共創',
  buildCom: '創建公社',
  jionCom: '加入公社',
  propertyStatus: '資金狀態',
}
