export default {
    timeleft:'預計',
    afterend:'後結束',
    endtime:'結束時間',
    bid:'立即出價',
    bidtime:'出價次數',
    available:'可用',
    trade:'交易',
    counttime:'倒計時長',
    bidrange:'加價幅度',
    auctionsystem:'拍賣方式',
    servicefee:'手續費/次',
    time:'次',
    favorites:'收藏',
    people:'人',
    bidders:'出價人數',
    viewers:'圍觀人數',
    bidrecord:'出價記錄',
    status:'狀態',
    in:'領先',
    out:'出局',
    price:'價格',
    location:'所在地',
    deposit: '充值',
    startprice:'起拍價格',
    pricelimit:'限價',
    nodata:'暫無數據',
    rules:'規則說明',
    currentbid:'當前價',
    fees: '手續費',
    ongoing:'進行中',
    tostart:'即將開始',
    ended:'已完成',
    pleaceLogin:'請先登錄',
    chexbalance:'CHEX可用餘額不足',
    newauction:'前往新項目',
    pay:'立即支付',
    paid:'已支付',
    paidfial:'支付失敗',
    paidexpires:'支付過期',
    system:' 升價拍',
    rules1:'1.所有數字貨幣競拍初始價均為0元起，每位用戶每次出價需消耗10 CHEX，每一下單行為最高可同時出價5次。增加出價次數時，倒計時長仍為10秒。舉例：出價時「出價次數」選擇「5」，競拍標的價格即增加0.05USDT，需消耗手續費50 CHEX，等待10秒倒計時。',
    rules2:'2.進入拍賣，當您出價後，即進入拍賣倒計時，該數字貨幣的計時器將被自動重置，計時器歸零時，即您成功拍得該數字貨幣。',
    rules3:'3.若競拍成功，請在競拍成功後24小時內以成交價購買數字貨幣，逾期視為自動放棄。',
    rules4:'4.當網絡出現如黑客惡意攻擊，自然災害，作弊拍賣等不可控原因時，CHAOEX平台有權取消本次拍賣，退回相關資產。',
    rules5:'5.每期拍賣需至少有一人出價，方可算有效交易。如無人出價，該期競拍取消。',
    rules6:'6.本活動最終解釋權歸CHAOEX平台所有。',
    listPage:{
      Winners_List:'榜單播報',
      All: '全部',
      Ongoing: '進行中',
      To_start: '即將開始',
      Ended: '已完成',
      Add_to_my_favorites: '收藏',
      View: '圍觀',
      My_participation: '我的參與',
      Win: '獲勝',
      Whitepaper: '白皮書',
      Current_bid: '當前價',
      Place_bid_times: '出價次數（次）',
      Highest_price: '最高限價',
      Start_price: '起拍價',
      Start_time: '開始時間',
      Earning_rate: '盈利約',
      Hammer_price: '成交價',
      Market_price: '市場價',
      Pay: '立即支付',
      Paid: '已支付',
      Payment_expired: '支付過期',
      First_page: '首頁',
      Last_page: '末頁',
    },
    payModal:{
      Auction_payment: 'Auction-支付',
      Congratulations: '祝賀您',
      Win: '可獲得',
      Available_balance: '可用餘額',
      Pay: '立即支付',
      Epay_transfer: 'Epay劃轉',
      Deposit: '充值',
    },
    plus:{
      hsjl:'獲勝記錄',
      auctionhsjl:'Auction獲勝記錄',
      zf:'支付',
      zfzt:'支付狀態',
      qb:'全部',
      dzf:'待支付',
      yzf:'已支付',
      zfgq:'支付過期',
      ms:'模式',
      rq:'日期',
      hdbd:'獲得標的',
      sycs:'剩餘次數',
      bdsl:'標的數量/份',
      cjjf:'成交價/份',
      zcs:'總次數',
      gkhd:'共可獲得',
      zcjj:'成交總價',
      mfsl:'每份數量',
      mfjg:'每份價格',
      qpsxf:'起拍手續費',
      jjfd:'加價幅度',
      rules:'規則說明',
      rules1:'1.所有數字貨幣競拍限定出價次數，指定首次出價的手續費，之後的每一出價消耗的手續費需比前一出價多消耗指定單位的手續費。每一出價次數均對應一個獎勵份額。每次出價後有10秒計時，當倒計時為0時，即競拍結束。結束後參與用戶均可按照獲取的份額購買標的，同時免費獲得不同比例的獎勵。',
      rules2:'2.進入拍賣，當您出價後，即進入拍賣倒計時，該數字貨幣的計時器將被自動重置，計時器歸零時，該競拍結束。',
      rules3:'3.若競拍結束，請在競拍結束後24小時內以規定價格購買所獲份額，逾期視為自動放棄。',
      rules4:'4.當網絡出現如黑客惡意攻擊，自然災害，作弊拍賣等不可控原因時，CHAOEX平台有權取消本次拍賣，退回相關資產。',
      rules5:'5.每期拍賣需至少有一人出價，方可算有效交易。如無人出價，該期競拍取消。',
      rules6:'6.本活動最終解釋權歸CHAOEX平台所有。',

    }
}







