export default {
   
  Popover_Quantity:'數量',
  Popover_Amount:'總金額',
  Popover_Average:'平均價格',
  PleaseLogin:'請先登錄',
  PleasePass:'請輸入交易密碼',
  theme: '主題顏色',
  dark: '黑',
  light: '亮',
  time: '時間',
  price0: '價格',
  amount1: '成交數量',
  buy: '買入',
  sell: '賣出',
  bestBuy: '最佳買價',
  bestSell: '最佳賣價',
  totalAmont: '金額',
  depth: '深度',
  deposit: '充值',
  property: '我的资产',
  free: '手續費',
  priceWarn: '價格輸入必須是',
  numWarn: '委託數量過低或超限',
  login: '登錄',
  priceNull: '請輸入委託價格',
  numNull: '請輸入委託數量',
  priceError: '價格錯誤',
  petl:'委託價格超出限制',
  openPrice1:'開盤價',
  Limit1:'漲跌限制',
  numError: '數量錯誤',
  pwdNull: '請輸入交易密碼',
  available: '可用',
  open: '未成交委託',
  tr: '成交記錄',
  type: '類型',
  price: '價格',
  price3: '委托價格',
  price2: '成交價格',
  amount: '數量',
  Or:'委托',
  amount3: '委托數量',
  status: '狀態',
  action: '操作',
  total: '委託金額',
  filled: '已成交數量',
  tPwd: '交易密碼',
  bPwd: '密碼',
  ok: '確認',
  before: '交易前请先',
  unfinished: '未成交',
  register: '注册',
  or: '或',
  pfinished: '部分成交',
  cancel: '撤單',
  completed: '全部成交',
  more: '更多',
  cancelOk: '撤單成功',
  price1: '限價',
  lPrice: '市價',
  equate: '可買',
  equate1: '可賣',
  lPriceMes: `<p>市价指不设定买入价格或卖出价格，按照</p>
    <p>当前的市场价格买入或卖出，只需输入想</p>
    <p>买入的总金额或卖出的总数量即可</p>`,
    transactionaAount: '成交金額',
    remainingAmount: '未成交數量',
    all: '全部',
    ipe: '郵箱或手機',
    ippwd: '密碼',
    fpws: '忘記密碼',
    rg: '立即註冊',
    Average:'成交均價',
    Turnover:'成交率',
    transactions:'成交數量',
    Batch:'批量撤單',
  delegation:'掛單',
  transaction:'成交',
  pletPwd:'請輸入交易密碼！',
  orclsPwd:'是否關閉交易密碼',
  cancleok:'您正在批量撤銷',
  cancleok2:'個委托單,',
  cancleok3:'是否確定撤銷？',
  contentPool:'自2018年12月1日至2019年3月31日期間，平臺交易手續費享受如下優惠：2018年12月1日至31日，交易手續費减免75%；2019年1月1日至31日，交易手續費减免50%；2019年2月1日至28日，交易手續費减免30%；2019年3月1日至31日，交易手續費减免10%.',
  chexFee:'使用CHEX抵扣交易手續費',
  di:'第',
  tian:'天',
  nowShow:'當日不再展示',
  decimals:'位小數',
  vol24h: '成交量',
  depthtotal:'成交额',
  Market:'市場',
  
  Yours:'我的',
}