export default {
  Mining_commune: '公社挖礦',
  Mining_commune_formally: '公社挖礦正式上線·瓜分15億',
  Accumulated_distribution: '累計派發',
  Distribution_of_yesterday: '昨日派發',
  Block_finding_commune: '爆塊公社',
  commune: '公社',
  nodata:'暫無數據',
  Not_available: '暫無',
  Rule_description: '規則說明',
  Rule_url: 'https://chaoex934.zendesk.com/hc/zh-cn/articles/360038181473-CHE%E7%A4%A6%E5%B7%A5%E5%85%AC%E7%A4%BE%E9%AB%94%E7%B3%BB%E8%A6%8F%E5%89%87%E8%AA%AA%E6%98%8E',
  Coming_soon: '敬請期待',
  Mining_is_ongoing: '挖礦進行中',
  Commune_leader_wanted: '公社管理招募中',
  Disbanded_Build_failed: '已解散/創建失敗',
  Build_commune: '創建公社',
  Current_commune_balance: '當前公社資金',
  Mining_duration: '挖礦時間：',
  Gains_of_yesterday: '昨日收益',
  Commission: '手續費',
  Full_up: '已滿',
  Join: '加入',
  create: '共創',
  Failed: '失敗',
  Commune_name: '公社名稱',
  Commission: '手續費',
  Choose_a_symbol: '選擇標誌',
  Can_not_be_changed: '選擇之後，不可變更',
  Mining_automatically: '30天公社滿(CHE)2000w自動開始挖礦，未滿則自動解散',
  Locked_quantity: '鎖倉數量',
  Currently_available: '當前賬戶可用',
  Transfer: '去劃轉',
  create_commune: '共創公社',
  Participate_in_commune: '參與共創',
  Join_in_commune: '加入公社',
  Remaining_positions: '剩餘管理倉位',
  Last_modification_time: '上次修改時間',
  Click_here_for_details: '點閱詳情',
  days_left: '還剩',
  The_commune_will: '未建成公社將自動解散',
  Notice:'須知：',
  Notice1:'1. 公社開始挖礦90天後社長可申請解散基石，31天後自動解散，延長解散期間仍可獲得挖礦收益和手續費。',
  // Notice2:'2. 社長有權設置手續費：範圍在0-30%，72小時內只能設置一次。',
  Notice3:'2. 挖礦比例隨着公社中幣的總數量增加而增加，封頂數量為每日135萬個。',
  Notice4:'3. 持幣 1 千以上，可申請加入公社成為社員，以 1 千的整數倍可加入。加入當天即可獲得挖礦收益，加入公社滿 30 天后可自由退出該公社，申請退出後，即刻生效，退出當日無收益。',
  Notice5:'4. 獎勵結算時間:獲得收益後，次日凌晨 1 點之後結算到賬，到賬後的收益可自由支配。',
  

  Please_input_commune: '請輸入公社名稱',
  Please_set_commission: '請輸入手續費',
  commission_range_is: '手續費在0-30%之間，請重新輸入',
  Insufficient_available_balance: '當前可用餘額不總，請去劃轉',
  Please_open_your: '請先開啟交易密碼',
  Trading_password: '交易密碼錯誤',
  The_remaining_position : '剩餘倉位不足，請重新輸入鎖倉數量',
  The_remaining_management: '剩餘管理倉位不足，請重新輸入鎖倉數量',
  The_lockups_number: '鎖倉數量在500w-1999w之間，請重新輸入',
  Transfer_succeed: '劃轉成功',
  Please_enter_the_correct_amount:'請輸入正確金額',
  Transfer_failed: '劃轉失敗',
  insufficient_transfereable_balance: '當前可劃轉余額不足',
  Creation_time: '創建時間：',
  Disband: '解散',
  Range_in_hours: '範圍在0-30%，下次設置72小時後',
  characters_can_not_be_changed: '2-10個字符，支持中英文數字，不可更改',
  Current_asset: '當前公社資金',
  Commune_Rank: '當前公社排名',
  participants: '人參與',
  Remaining_postitions: '剩餘倉位:',
  Block_finding_and_profits:'爆塊和收益',
  Block_finding_and_profits1:'1) 爆塊:公社中 CHE 數量最先達到 2 億封頂數量的前三個公社，為爆塊公社，分別可獲得 2000 萬、1000 萬、500 萬個 CHE 幣。',
  Block_finding_and_profits2:'2) 收益分配:該公社中全部用戶按自己在該公社中持有的 CHE 數量占該公社總 CHE 幣數量(2 億)的比例，分得爆塊收益，減去手續費後，即為爆塊收益。管理團隊按照比例獲得用戶繳納的手續費。',
  Block_finding_and_profits3:'3) 限制規則:同一個公社只能獲得一次爆塊機會，同一個用戶可多次參與爆塊公社。',
  Block_finding_and_profits4:'4) 獎勵結算時間:滿足 2 億後，次日凌晨 1 點之後結算到賬，到賬後的收益可自由支配。',
  Block_finding_and_profits5:'5) 爆塊總收益 1800 萬包含在挖礦的總量 15 億中。',

}

