export default {
    title:'选择验证方式',
    old:'交易密碼',
    aNew:'邮箱',
    ivc:'圖片驗證碼',
    evc:'验证码',
    sv:'獲取驗證碼',
    ss:'確認提交',
    msg:'為了您的資產安全，交易密碼修改後24h以內不允許提現',
    pwdMsg:'密碼由6-18數字、字母和特殊字符組成',
    sMsg:'密碼不一致',
    imgMsg:'圖片驗證碼有誤',
    emaMsg:'郵箱驗證碼有誤',
    send:'發送',
    way:'驗證方式',
    emil:'验证邮箱',
    ph:'验证手机',
    pl:'請選擇',
    pvc:'手機驗證碼',
    errorMsg:'驗證碼有誤',
    pNew:'手机',
    
}