export default {
  UPA:'了解權限認證',
  Reviewing:'審核中',
  nV: '未認證',
  v: '已認證',
  lg: '最後一次登錄',
  sD: '完成身份認證',
  dw: '日提幣限額',
  hw: '可享受更低費率與更高提幣限額',
  cu: '聯系我們',
  svd: '完成身份認證',
  msg: '請不要透露密碼、短信和谷歌驗證碼給任何人，包括我們的工作人員。',
  tA: '總資產',
  aR: '資產記錄',
  d: '充值',
  deal: '可充值，交易',
  haveComplate: '已認證',
  haveComplatePerson: '完成視頻認證',
  kyc1: '請先完成KYC.2的認證',
  ylnn: '您的鎖倉節點數',
  plnn: '平台鎖倉節點總數',
  ptlnn: '平台今日單節點收益',
  nm: '節點管理',
  node: '節點',
  account: '賬戶',
  safe: '安全',
  invite: '邀請',
  fee_1: '交易手續費0.1%',
  fee_2: '交易手續費0.075%',
  fee_3: '交易手續費0.05%',
  base: '基礎認證',
  person: '身份認證',
  video: '視頻認證',
  goto: '認證',
  gu: '總資產折合',
  successful: '成功邀請',
  code: '我的邀請碼',
  inviteFriend: '邀請好友返佣',
  inviteMoney:'邀請註冊，輕鬆返佣',
  loginRecord: '登錄記錄',
  securityRecord: '安全設置記錄',
  revenueRecord: '收益記錄',
  userMes:`<p>2019年1月31日前，完成KYC 2级认证，</p>
  <p>可获得1 USDT奖励完成KYC </p>
  <p>3级认证，可获得2 USDT奖励。</p>`,
  chexFee:'使用CHEX抵扣交易手續費',
  abolish:'取消',
}
