export default {
   
  Popover_Quantity:'数',
  Popover_Amount:'総金額',
  Popover_Average:'平均価格',
  PleaseLogin:'まず登録してください',
  PleasePass:'取引のパスワードを入力してください。',
  theme: 'テーマの色',
  dark: '黒い',
  light: '明るい',
  time: '時間',
  price0: '価格',
  amount1: '出来高',
  buy: '買い入れる',
  sell: '売りに出る',
  bestBuy: '最高の買値',
  bestSell: 'ベスト売価',
  totalAmont: '金額',
  depth: '深さ',
  deposit: 'チャージ',
  property: '私の資産',
  free: '手数料',
  priceWarn: '価格入力は必ず',
  numWarn: '委託数量が低すぎたり、制限が超過したりします。',
  login: 'ログイン',
  priceNull: '委託価格を入力してください。',
  numNull: '委託数量を入力してください。',
  priceError: '価格が間違っています',
  petl:'委託価格が制限を超えている',
  openPrice1:'寄り付き相場',
  Limit1:'上げ下げ制限',
  numError: '数量が間違っています',
  pwdNull: '取引のパスワードを入力してください。',
  available: '利用可能',
  open: '未成約依頼',
  tr: '取引記録',
  type: 'タイプ',
  price: '価格',
  price3: '委託価格',
  price2: '成約価格',
  amount: '数',
  Or:'委託する',
  amount3: '委託数量',
  status: '状態',
  action: '操作',
  total: '委託金額',
  filled: '取引済みの数量',
  tPwd: '取引パスワード',
  bPwd: 'パスワード',
  ok: '確認',
  before: '取引前にまず',
  unfinished: '取引が成立していない',
  register: '登録する',
  or: 'または',
  pfinished: '部分的な取引',
  cancel: '帳消しにする',
  completed: '全部成約する',
  more: '詳細',
  cancelOk: 'キャンセル成功',
  price1: '価格を限る',
  lPrice: '市価',
  equate: '買うことができます',
  equate1: '売れる',
  lPriceMes: `<p>市价指不设定买入价格或卖出价格，按照</p>
    <p>当前的市场价格买入或卖出，只需输入想</p>
    <p>买入的总金额或卖出的总数量即可</p>`,
    transactionaAount: '取引高',
    remainingAmount: '未成約数量',
    all: '全部',
    ipe: 'メールアドレスまたは携帯電話',
    ippwd: 'パスワード',
    fpws: 'パスワードを忘れます',
    rg: '即時登録',
    Average:'成約価格',
    Turnover:'成約率',
    transactions:'出来高',
    Batch:'ロット撤収書',
  delegation:'注文書を出す',
  transaction:'取引が成立する',
  pletPwd:'取引パスワードを入力してください。',
  orclsPwd:'取引パスワードを閉じますか？',
  cancleok:'一括キャンセル中です。',
  cancleok2:'個委托單,',
  cancleok3:'キャンセルしますか？',
  contentPool:'2018年12月1日から2019年3月31日までの間、プラットフォーム取引手数料は以下のように優遇されます。2018年12月1日から31日まで、取引手数料は75%減免されます。2019年1月1日から31日まで、取引手数料は50%減免されます。2019年2月1日から28日まで、取引手数料は30%減免されます。',
  chexFee:'CHEXを使って取引手数料を差し引きします。',
  di:'第',
  tian:'空',
  nowShow:'当日は展示しません',
  decimals:'ビット数',
  vol24h: '出来高',
  depthtotal:'出来高',
  Market:'市場',
  
  Yours:'私の',
}