export default {
    feedback:'フィードバック記録',
    qus:'問題の種類',
    dec:'問題の説明',
    qus1:'検証問題',
    qus2:'チャージ',
    qus3:'現金で出す',
    qus4:'注文書',
    qus5:'取引',
    qus6:'アカウント',
    qus7:'その他',
    upload:'写真をアップロード',
    me:'私',
    service:'顧客サービス',
    say:'何を言いますか',
    ask:'追問',
}