import Header from './header'

export default {
    ...Header,
    hp: 'ヘルプ',
    text_1:'サービスホットライン：+852 2561 1995',
    text_2:'市場協力：+852 2562 9855',
    address:'香港銅鑼湾告士打道223号海聯ビル',
    nr: '登録人数',
    business:'ビジネス提携',
    notice:'法律上の声明',
    rate:'料率説明',
    privacy:'プライバシー条項',
    us:'私たちについて',
    download:'Android(このダウンロードをクリックしてください)',
    ios:'IOS（ここでダウンロードする）',
    load:'ローカルダウンロード',
    email_1:'support-cn@chaoex.com.hk',
    email_2:'busines-cn@chaoex.com.hk',
    unusual: '取引異常処理',
    API:'APIドキュメント',
    dw:'チャージ&現金引き出し',
    dh:'チャージ記録',
    wh:'現金引き出し記録',
    fd:'資産管理',
    ac: 'センター',
    ss: 'セキュリティ設定',
    vd: '実名認証',
    od: '委託する',
    th: '取引記録',
    center:'サポートセンター',
    announcement:'公告する',
    faq:'FAQ',
    code:'コードについて',
    apidoc: 'APIアプリケーション',
    transaction:'委託記録',
    companyEmail:'サービスメールボックス',
    bussinessWith:'ビジネス提携',
    cnuri:'support-cn@chaoex.com.hk',
    cnbus:'busines-cn@chaoex.com.hk',
    ng: 'ナビゲータ',
    down: 'クライアントをダウンロード',
    fl: '関心を持つ',
    procenter:'資産センター',
    info:'BTC情報',
    risk:'リスク開示',
    pow:'POWコンセンサス連盟メンバー', 
    jui:'ブロックチェーンに興味があれば、ご参加ください。',
    Applytolist:'上幣申請',
}