export default {
    confirmSub:'を選択します',
    PerCen:'センター',
    DownApp:'1.アプリのダウンロード・インストール',
    sQc:'2.二次元コードをスキャンする',
    BK:'3.バックアップキー',
    OpenG:'4.Googleの検証を開始する',
    HaveApp:'アプリをインストールしました',
    HaveQR:'二次元コードスキャンを完了しました。',
    HaveKey:'16ビットの鍵を覚えました。',
    Next:'次のステップ',
    CloseGA: 'Googleの認証をオフにします',
    login: 'ログインパスワード',
    gaCode: 'Googleの認証コード',
    submit: '縛りを解く',
    bindGA: 'Googleバインディング検証',
    download: 'Googleの検証アプリをダウンロードしてインストールします。',
    clickDownload: 'このダウンロードをクリックしてください',
    scanCode: 'Googleの検証APPを使って下の二次元コードをスキャンします。',
    secretKey: '鍵',
    enterPassword: '16ビットの鍵を正確に紙に記録し、適切に保管してください。もし携帯電話がなくなったら、この鍵を通じてGoogleの認証を回復できます。',
    enterCode: 'Googleの認証コード',
    modalText: 'あなたのアカウントの安全のために、二次認証を開くことを強く勧めます。',
    modalText1: 'ご希望の二次認証方式を選択してください。',
    iKnow: 'リスクを承知しています。',
    noSet: '設定を見合わせる',
    bindMess: '二次元コードをスキャンできない場合、Google認証APPに鍵を手動で入力できます。',
    bindMess1: 'または鍵を入力します',
    tips: '暖かいヒント',
    bindPhone:'携帯を結び付ける',
    bg:'携帯番号はすでにバインドされています。',
    bag:'Google認証がバインディングされました。',
    guAuthPwd:'ログインパスワードを記入してください。',
    guAuthCode:'Googleの検証コードを記入してください。',
    next:'次のステップ',
    nostrum:'Googleの顧客サービスをリセットします。書類を提出する必要があります。少なくとも7日間はかかります。',
    way:'認証方式',
    Vemail:'メール認証',
    VSMS:'携帯認証',
    AVC:'認証コードを取得',
    pl:'選択してください',
    errorMsg:'認証コードが間違っています',
    dts:'ドラッグします',
    dtr:'右ドラッグ',
    uf:'読み込みに失敗しました',
    uld:'読み込み中',
    civ:'CHA OEX無感検証',
    ck:'知能検査中',
    vs:'認証に成功しました',
    vf:'認証に失敗しました',
    vip:'認証中',
    mnn:'メールボックスは空にできません',
    pnn:'携帯は空です',
    send:'送信',
    successGa:'Googleは検証を開始しました。3 s後に「個人センター」に戻ります。',
    errorGa:'Googleの検証オープンに失敗しました。3 s後に「個人センター」に戻ります。',
    successClose:'Googleの検証が終了しました。3 s後に「個人センター」に戻ります。',
    errorClose:'Googleの検証閉鎖に失敗しました。3 s後に「個人センター」に戻ります。',
    sv:'検証コードを取得する',
}