export default {
    tc: '取引センター',
    h: '最初のページ',
    lg: 'ログイン',
    rg: '登録する',
    fd: '資産管理',
    dw: 'チャージ&現金引き出し',
    dh: 'チャージ記録',
    wh: '現金引き出し記録',
    th: '取引記録',
    pi: '個人',
    od: '委託する',
    ns: 'ヘルプ',
    Mining_commune: '公社が採掘する',
    center:'サポートセンター',
    ac: 'センター',
    lgt: '終了',
    ss: 'セキュリティ設定',
    vd: '実名認証',
    logout: 'ログアウト成功',
    announcement:'公告する',
    invite:'親友を招く',
    aboutCode: 'コードについて' ,
    gawt:'取引依頼記録',
    app:'まずAPPに行ってください。ご理解とサポートに感謝します。',
    s:'設定',
    theme:'テーマ',
  black:'ブラック',
  white:'ホワイト',
  cur:'法貨の切り替え',
  submit: '確認',
  getsuccessed:'受取成功',
    discount:'割引申し込み',
    newCoin:'新区を開く',
    bbwd:'割引申請BTC活動',
    endtime:'今回のイベント終了時間',
    day:'空',
    alq:'ロックに使用できます',
    afpq:'申し込みに利用できます',
    number:'数',
    lockedn:'今回のロック数',
    lock:'アンカー',
    pci:'今回の通貨申請の情報',
    token:'トークンの名前',
    cl:'発行量/流通量',
    apq:'申請可能数量',
    ql:'数量/ラベル',
    pp:'申し込み価格/枚',
    op:'寄り付き相場/枚',
    mwl:'単一口座の最大落札数',
    petnop:'申し込み数量を入力してください。',
    purchase:'購入を申請する',
    mpr:'私の申請記録',
    data:'申し込み期日',
    spl:'成功申請署名数',
    ta:'総金額',
    ad:'活動細則',
    ls:'ロック成功',
    ps:'申し込み成功',
    st:'現物取引',
    iusertotal:'招待有効ユーザー総数',
    usdtPur:'US DTの申し込み',
  chexPur:'CHEXの申し込み',
  CHEX_Loan:'chexローン',
  Follow:'コミュニティ群',
  Support:'工商証書',
  Locked_assets_revenue:'安定の宝',
  Assets_revenue:'まばたきする宝物',
  Fiat_Convert:'仏貨取引',
  Financial_Center:'投資信託センター',
  alert: 'まずKYC 2認証を行ってください。',
  PleaseLogin:'まず登録してください',
  PleasePhone:'まず携帯番号を結びつけてください。',
  imgUrl:'https://coinmarktcap.com/zh/exchanges/chaoex/',
  whitepaper:'白書',
}
