export default {
  Mining_commune: '共同通信社が採掘する',
  Mining_commune_formally: '公社が鉱山を掘るのは正式にオンラインします。',
  Accumulated_distribution: '累計配給',
  Distribution_of_yesterday: '昨日配る',
  Block_finding_commune: '爆塊公社',
  commune: '公社',
  nodata:'データがありません',
  Not_available: 'しばらく',
  Rule_description: 'ルールの説明',
  Rule_url: 'https:/chaoex 934.zendes.com/hc/zh-cn/articales/360081473-CHE%E 7%E 6%E 5%B 7%E 5%E 5%E 7%E 7%A 4%E 9%E 7%E 7%E 7%E 7%B 3%E 8%E 8%E 8%A 8%E 89%',
  Coming_soon: 'お楽しみに',
  Mining_is_ongoing: '採掘中',
  Commune_leader_wanted: '公社管理募集中です。',
  Disbanded_Build_failed: '解散する/作成に失敗しました。',
  Build_commune: '公社を創立する',
  Current_commune_balance: '当面の公社資金',
  Mining_duration: '採掘時間：',
  Gains_of_yesterday: '昨日の収益',
  Commission: '手数料',
  Full_up: 'もう満員です',
  Join: '加入する',
  create: '共に創る',
  Failed: '失敗',
  Commune_name: '公社の名称',
  Commission: '手数料',
  Choose_a_symbol: '選択フラグ',
  Can_not_be_changed: '選択後、変更できません。',
  Mining_automatically: '30日間で公社が満2000 wになり、自動的に掘削が始まり、満期でないと自動的に解散します。',
  Locked_quantity: 'ロック数量',
  Currently_available: '現在のアカウントが使えます',
  Transfer: 'こぎに行く',
  create_commune: '共同通信社をつくる',
  Participate_in_commune: '共創に参与する',
  Join_in_commune: '公社に入る',
  Remaining_positions: '残り管理ポジション',
  Last_modification_time: '前回の修正時間',
  Click_here_for_details: '詳細を調べる',
  days_left: 'まだ残っています',
  The_commune_will: '公社が完成していないと自動的に解散します。',
  Notice:'注意事項：',
  Notice1:'1.公社が掘削を開始して90日後に社長が解散の礎石を申請でき、31日後には自ら解散し、解散期間を延長しても採掘の収益と手数料を得ることができる。',
  // Notice2:'2.社長は手数料を設定する権利があります。範囲は0-30%で、72時間以内は一回しか設置できません。',
  Notice3:'2.採掘の割合は公社の中貨幣の総数量の増加とともに増加し、上限の数は毎日135万個である。',
  Notice4:'3.1000円以上のお金を持っています。公社に入社して社員になることを申請できます。1000倍の整数で加入できます。加入当日に採掘の収益が得られます。公社に加入してから30日後には自由にこの公社を脱退し、脱退を申請したら即効し、当日には収益がありません。',
  Notice5:'4.決算の奨励期間：収益を獲得した後、翌日の午前1時以降に決算し、入金後の収益は自由に支配できる。',
  

  Please_input_commune: '社名を入力してください。',
  Please_set_commission: '手数料を入力してください',
  commission_range_is: '手数料は0-30%の間です。もう一度入力してください。',
  Insufficient_available_balance: '現在利用可能な残高が合計されていませんので、振り替えてください。',
  Please_open_your: 'まず取引パスワードを開けてください。',
  Trading_password: '取引パスワードが間違っています',
  The_remaining_position : '残りの倉庫が足りないので、改めてロック数量を入力してください。',
  The_remaining_management: '残りの管理倉庫が足りないので、改めてロック数量を入力してください。',
  The_lockups_number: 'ロック数量は500 w-1199 wの間にあります。もう一度入力してください。',
  Transfer_succeed: '振り替え成功',
  Please_enter_the_correct_amount:'正しい金額を入力してください。',
  Transfer_failed: '振り替え失敗',
  insufficient_transfereable_balance: '現在振替可能残高が不足しています。',
  Creation_time: '作成時間:',
  Disband: '解散',
  Range_in_hours: '範囲は0-30%で、次回は72時間後に設定します。',
  characters_can_not_be_changed: '2-10文字で、中国語と英語の数字をサポートします。変更できません。',
  Current_asset: '当面の公社資金',
  Commune_Rank: '現在の公社ランキング',
  participants: '人参と',
  Remaining_postitions: '残りの倉位:',
  Block_finding_and_profits:'バーストと収益',
  Block_finding_and_profits1:'1）爆発ブロック：公社の中でCHEの数が最初に2億の上限数に達した最初の3つの公社は、爆発ブロック公社であり、それぞれ2000万、1000万、500万のCHE貨幣を獲得することができる。',
  Block_finding_and_profits2:'2）収益分配：当該公社の全ユーザーは、当該公社の総CHE貨幣数（2億）に対して、自分が保有するCHEの数に比例して、ブロックの爆発収益を得て、手数料を差し引いた後、即ちブロックの爆発収益となる。管理チームは比例によって、ユーザが支払う手数料を獲得します。',
  Block_finding_and_profits3:'3）制限規則：同じ公社では一回の爆発ブロック機会しか得られません。同じユーザーは何度も爆発ブロック公社に参加できます。',
  Block_finding_and_profits4:'4）奨励決算期間：2億を満足した後、翌日の午前1時以降に決算し、帳簿に着いた後の収益は自由に支配できる。',
  Block_finding_and_profits5:'5）爆発塊の総収益は1800万元で、採掘の総量は15億中に含まれている。',

}

