export default {
  selectAdd:'選択されたトークンの住所',
  Adda:'+アドレスを追加',
  kmd:'活動の詳細を知るには…',
  copyText:'コピー',
  affirm:'を選択します',
  abolish:'キャンセル',
  geschw:'取り上げる供可能データがありません。',
  Deposit:'チャージ',
  withdrawals:'現金で出す',
  changeEx:'両替する',
  proBack:'資産センター',
  title: 'チャージ&現金引き出し',
  Title: 'チャージ記録',
  dw: '毎日の貨幣の限度額',
  Balances: '既存の資産のみを表示します。',
  CapitalRecord:'資産流水記録',
  gu: '総資産換算',
  to: 'を選択します',
  all: '全部',
  withdraw: '現金引き出し記録',
  property: '資産センター',
  entrust: '現在の依頼',
  current: '履歴依頼',
  deal: '取引記録',
  unFinished: '未完成',
  finished: '完了しました',
  transaction: '取引依頼記録',
  iu: '今日はすでに引き出し額を使っています。',
  searchCur:'通貨を検索する',
  status: '状態',
  type: 'チャージ/タイプ',
  Deposits: '充電する',
  choice: 'リアチャージタイプを選択してください。',
  noRecord: 'データを提供できません。',
  Withdrawals: '提',
  pay: '貨幣をチャージする',
  sell: '貨幣を受け取る',
  Trade:'取引',
  much:'詳細',
  coin: '貨幣種類',
  action: '操作',
  fullName: '全称',
  totalAsset: '総額',
  available: '利用可能',
  availabledown: '利用可能な数',
  Assets: '既有資産',
  inOrder: '凍結する',
  copy: 'クリックしてコピーします',
  payAddress: 'チャージアドレス',
  last: 'チャージが完了したら、履歴ページに入って進捗を追跡してください。',
  text_1: '使用',
  text_2: '住所のチャージが必要です',
  text_3: '非',
  text_4: '資産は取り戻せない。',
  text_5: '禁止方向',
  text_6: 'アドレスチャージ',
  text_7: '以外の資産については、いかなる充当も',
  text_8: '住所の',
  text_9: '以上のネットで確認してから入金できます。',
  sellAddress: '現像住所',
  Withdrawal: '現金で出す',
  sellText: '今回の提出先を下に入力してください。',
  lable: 'メモラベル',
  address: '住所',
  amount: '数',
  max: '全部現金にする',
  tradePassword: '取引パスワード',
  fees: '手数料',
  submit: '送信',
  willGet: '実際に入金する',
  done: '現在完了したら、履歴ページに入って進捗を追跡できます。',
  minCoin: '最小貨幣数は',
  notFound: 'なし',
  ivc: '画像認証コード',
  sv: '認証コードを取得',
  sellTitle: '現像住所',
  evc: 'メールアドレス',
  send: '送信',
  alert: 'まずKYC 2認証を行ってください。',
  success: 'お札の引き出しに成功しました',
  fee: 'インターネット手数料',
  google: 'Google',
  way: '認証方式',
  emil: 'メールボックス',
  ph: '携帯電話',
  pvc: '携帯の認証コード',
  pd: '（ChoExから他のプラットフォームに転送するには必要です）',
  tp: '（記入しないと入金できません。)',
  pl: '選択してください',
  t_1: 'チャージ手順：',
  t_2: 'チャージアドレス',
  t_3: '（必ず記入してください）',
  t_4: '3.その他の情報を記入し、チャージを完了する',
  t_5: '1.記入',
  t_6: '2.記入',
  a: '全部',
  y: '既有資産',
  f: 'フォーク・コイン',
  plp: '携帯電話と結びつけてください',
  plo: 'Google認証をバインドしてください。',
  ratio: '為替レート',
  ea: '両替量',
  safe: 'ネットを張って両替する',
  ec: '両替する',
  lab1: '該当数量を消耗します。',
  lab2: '資産、本人はリスクをすでに知っていて、両替をを選択しますします。',
  pld: '取引のパスワードを入力してください。',
  ppo: '取引パスワードを開けてください。',
  apply: '申し込み',
  unlock: '倉庫を解く',
  ylnn: 'あなたのロックポイント',
  ChexTotal:'CHEXロック倉庫総量',
  plnn: 'プラットフォームロックノード総量',
  ptlnn: '昨日のシングルノード収益',
  nm: 'ノード管理',
  node: 'ノード',
  annan: '数量は空であってはいけません',
  dpnn: '取引のパスワードは空ではいけません。',
  applynumerror: '＊数量が間違っています。整数を入力してください。',
  applyS: 'ノードの成功により、ノードロックの有効期間は明日の0時となります。',
  lnnan: '解凍ノードの数は空であってはいけません。',
  locknumerror: '*解凍ノードの数が間違っています。解凍ノードの整数を入力してください。',
  giveupnode: '倉庫を解く後はロック時間とノードで採掘収益を放棄します。解倉ノードを確認してください。',
  nodeS: '解倉ノード成功',
  cnum: '利用可能な数',
  sd: '初期収益日',
  ann: 'ロック申請数（万）',
  anNumber: '申請ノード数',
  clocknum: 'リムーバブルノード数',
  clocknums: '解凍ノード数',
  clocknumber: '解凍ノード数',
  locknum: 'ロックポイント',
  dp: '取引パスワード',
  transfer: 'レコードを振り替える',
  app: 'まずAPPに行ってください。ご理解とサポートに感謝します。',
  transferbtn: '振り回す',
  configinfo: '両替情報を確認する',
  changecode: '両替コードの数量',
  changeusdt: '両替の数',
  nowprice: 'リアル？タイム？チェンジ',
  getusdt: 'US DTを取得した数',
  getcode: 'コードの数を得る',
  cancle: 'キャンセル',
  sureconfig: '確認',
  usdtsure: '両替価格はUSDTのリアルタイム価格によって両替します。',
  CHEXnodesmanagement: 'CHEXノード管理',
  rewardCenter:'資産特別区を奨励する',
  youtotal: '総収益',
  InRecord:'収益記録',
  youreven: '未払収益',
  nodeList: 'ノードリスト',
  RevernueRecord: '収益記録',
  chexNode: '*10万CHEX=1ノード',
  applyNode: 'ロックを申請する',
  unlockNode: '解倉ノード',
  Nodes:'ノード',
  hintOne: '1.ノードのロック時間は申請の日から翌日の00:00から有効となります。',
  hinttwo: '2.連続して倉庫をロックして30日後に収益を開始し、収益は翌日の昼12時に支給される。',
  hintScheme: '解倉案に同意してチェックしてください。',
  applyTime: '申し込み時間',
  applyNodeNum: '申請ノード数',
  lockNodeNum: 'ロックポイント',
  earnings: '総収益（CHEX）',
  stayOut: '未払収益',
  beginTime: '初期収益日',
  serNum: '番号付け',
  nodeStatus: 'ノードの状態',
  lockPer: 'ロック日数',
  totalChex: '総収益（CHEX）',
  lockTime: '解倉時間',
  locking: '倉庫にかぎをかける',
  unlocking: '解倉',
  nodesure: '優先的に解凍申し込み時間が一番遅いノードを本人が知っています。',
  entrustRecord: '委託記録',
  EarningsYesterday: `<p>ルールによって、昨日まで23:59:59鍵仓満30日間のノード同点昨日500000 chexインセンティブを与える。1ノードあたりの報酬計算式=500,000 CHEX /条件を満たすノード数。</p>`,
  revenue:'節點收益',
  minTranferIn:'最小繰越数は',
  minTranferOut:'最小転出数は',
  doneTranfer: '振り替えが完了したら、履歴ページに入って進捗を追跡できます。',
  epayTran:'Epayスイープ',
  epayTranUUEX:'UUEXスイープ',
  tranIn:'繰り越す',
  tranOut:'転出する',
  sureIn:'入金確認',
  sureOut:'転出確認',
  doneTranferIn:'移動が完了したら、履歴ページの進捗状況を追跡してください。',
  doneTranferOut:'転送が完了したら、履歴ページの進捗状況を追跡します。',
  gotoEpay:'お支払いはEpay公式サイトでお願いします。',
  go:'直ちに赴く',
  aTime:'申請時間',
  epayType:'タイプ',
  outAccount:'入金Epayアカウント',
  account:'Epayアカウント',
  n:'コメント',
  formatError:'Epayアカウントのフォーマットが間違っています。',
  pinputEpay:'Epayアカウントを入力してください',
  addaccount:'Epayアカウントを追加',
  epayFormatErr:'Epayアカウントのフォーマットが間違っています。',
  addsu:'Epayアカウントの追加に成功しました。',
  tranoutsu:'転出成功',
  epayRecord:'Epay記録',
  epin:'Epay転入',
  epout:'Epay転出',
  numerr:'数量入力エラー',
  plerr:'Epayアカウントを入力してください',
  noopenepay:'Epayアカウントが未開通です',
  goregiepay:'登録します',
  aword:'資産特別区を奨励する',
  applyL1:'1、利息計算：自然日数に基づいて計算し、ロック期日当日を含み、期日当日を含まない。',
  applyL2:'2、解凍による収益：期日当日の14:00に整理し、プラットフォームはユーザーの元本と収益を自動的にユーザー口座に配布する。',
  wenxirule:'CHA OEXにCHEXを保有している場合、ロックは半年で年10%の収益を享受できます。ロックは1年で、年12%の収益を享受できます。満期になったら、同時に元利と利息を支払うことができます。ロック数量：毎回ロックは10万CHEX以下で、ロック量を増加できます。超過部分は1万倍です。',
  shanrule:'1.CHA OEXの持ち場総資産等の価値が300 USDTのユーザーに多い場合、毎日年6%のボーナスを享受し、CHEXに換算して個人口座に発給することができます。毎日の24:00はユーザーの保有資産の数量を快速に照らして、当時の市場価格によって計算します。条件を満たすユーザーは毎日年6%の賞与を享受します。スナップショット時間：毎日24:00 3.USDT価格を両替します。CHAOEX毎日24:00の市場価格で等値計算します。CHEX価格を両替します。CHEX毎日平均価格=当日CHEX取引総額/当日CHEX取引総額5.統計範囲：利用可能な資産とシングル資産を持って奨励範囲に計上します。出産は奨励の範囲に算入しない',
  paydrowMes:`<p>2019年1月31日前，完成KYC 2级认证，</p>
  <p>可获得1 USDT奖励完成KYC </p>
  <p>3级认证，可获得2 USDT奖励。</p>`,
  awardDtail:'奨励の内訳',
  awardProperty:'総資産を奨励する',
  shan:'まばたきする宝物',
  shanRecord:'収益記録',
  shan1:'累計収益（CHEX）',
  shan2:'昨日の資産（USDT）',
  shan3:'昨日の収益(CHEX)',
  shan4:'両替CHEX価格（USDT）',
  shanBtn:'受け取ります',
  wenCal:'ロック収益=すでに収益+予想収益',
  alGet:'受け取り済み',
  wen:'安定の宝',
  wenRecord:'ロック記録',
  wen1:'総収益（CHEX）',
  wen2:'収益（CHEX）',
  wen3:'収益予想（CHEX）',
  wenBtn:'ロックを申請する',
  lishi:'歴史活動',
  lishi1:'ノード管理',
  lishi2:'あなたのロックポイント',
  lishi3:'CHEXロック総数',
  lishi4:'総収益（CHEX）',
  lishi5:'未払収益（CHEX）',
  lishiRecord:'収益記録',
  more:'ノードレコード',
  minLock:'最小ロックは10万CHEXです。',
  lockPerid:'ロックサイクル',
  month1:'月',
  intrate:'年利率',
  roi:'予想収益：',
  sure:'確定',
  not300:'200未満のUSDT',
  minnum:'数量は10以下にしてはいけません',
  pstp:'まず取引パスワードを設定してください。',
  XLMCOIN:'現在は住所ラベルだけをサポートしています。他のタイプの住所ラベルはチャージできません。XLMチャージはpayment取引の種類のみ対応していますので、他の取引の種類（pathpaymentなど）はチャージできません。ご了承ください。',
  step1:'第一歩',
  s1:'GRINを上の住所に振り込んでください。',
  step2:'第二のステップ',
  s2:'振替情報に基づき、振替注文書を記入します。',
  step3:'第三歩',
  s3:'完了します。',
  endInfo:'プラットフォームが入金を確認したらチャージ記録が表示されます。',
  txidplh:'提元のハッシュ値を記入してください。',
  amountplh:'チャージの数',
  nodedetail:'奨励の内訳',
  auctionRecord:'コレクション優勝記録',
  info_modal_title:'尊敬するユーザー、',
  info_modal_content:'口座資金のリスクを低減するために、あなたの資産の安全を保証します。CHA OEXプラットフォームは現在の段階で貨幣調達サービスを人工審査処理に変えています。私たちは申請の時間順に、ユーザーの貨幣調達の需要を一つ一つ処理します。',
  Tran:'振り回す',

  mingmgr:'公社掘削管理',
  cashmount: '採掘口座利用可能残高',
  allproperty: '総資産',
  gotrans: 'こぎに行く',
  gomining: '採掘に行く',
  miningclubfrzen: '採掘公社が凍結する',
  yesProfit: '昨日の収益',
  yesProfitrate: '昨日の収益率',
  cumulate : '収益を累計する',
  clubmgr: '公社の名称',
  clubStatus: '公社状態',
  inmining: '採掘中',
  inenjoy: '募集中です',
  dismissed: '解散するしました',
  miningtime: '採掘時間',
  rank: 'ランキング',
  currentawardpool: '現在の公社資金プール',
  bemgr: '管理投入として',
  beclubor: '社員として投入する',
  cumulateinvest: '投入累計',
  cumulateProfit: '収益を累計する',
  profitrate: '収益率',
  yesAllprofit: '昨日の総収益',
  awardprofit: 'ボーナス',
  operation: '操作',
  cashrecord: '資金の流れ',
  setfee: '設置手数料',
  currentfee: '当面の手数料',
  inputnum: '振り替え数量を入力してください。',
  nextfor72h: '範囲は0-30%で、次回は72時間後に設定します。',
  currentLockamount: '現在の公社のロック金額',
  cangoutamount: '脱退可能金額',
  lockover30: '採掘ロックが満30日後に社員資金を払い戻すことができます。',
  lookinverstdetail: '投入明細を見る',
  sureafterprofit: '確認後,立即生效,終了當日無收益',
  outclub: '当面の公社を脱退する',
  discurrentclub: '当面の公社を解散する',
  clubminingtime: '公社掘削時間',
  applydisstime: '申請後の解散時間',
  scope30: '範囲は0-30%です',
  disband: '解散',
  join: '加入する',
  Exit: '退出',
  feeprofit: '手数料収益',
  awardpro: 'TOP奨励収益',
  boomawardpro: 'バースト奨励収益',
  cluballprofit: '公社総収益',
  clubperson: '公社人数',
  lastsetfeetime: '最終設定の手数料は時間がかかります。',
  clubcreatetime: '公社の作成時間',
  clubdistime: '公社解散時間',

  transRecord: '記録を振り替える',
  incomRecord: '収益記録',
  inputRecord: '投入記録',
  miningprof: '採掘収益',
  poverincom: '昨日の収益率=昨日の総収益/昨日の採掘中のロック量*100%',
  povermgr1: '累計総収益/収益率：未掘削鉱山公社のこの収益率なし=現在の公社の累計総収益/現在の公社の累計投入*100%',
  povermgr2: '昨日の総収益/収益率：昨日の未掘削鉱山公社のこの収益率=現在の公社昨日の総収益/現在の公社は昨日までの累計投入*100%',
  povermgr3: '手数料：公社社長は72時間以内に一度だけ調整できる権利があります。',
  povermgr4: '特別奨励収益：手数料収益（社員としてこの収益を投入しない）、爆発奨励収益、TOP奨励収益を含む',
  povermgr5: '状態：採掘中、募集中、作成失敗、解散しました。その中で採掘中の公社だけが収益を生みます。',
  povermgr6: '以下の収益計算はすべて個人収益です。',
  Exchangebalances: '貨幣の口座',
  Miningbalances: '採掘口座',
  notfee: '振替には手数料はかかりません。',
  cannotundo: 'この操作は元に戻せません。',

}
