export default {
  rekhw:'データを提供できません。',
  searchCur:'貨幣を選択する',
  title: 'チャージ記録',
  date: '時間を選択',
  allCoin:'全部',
  to: 'を選択します',
  coin: '貨幣種類',
  status: 'タイプを選択',
  typeC:'タイプ',
  finished: '完了しました',
  unFinished: '未完成',
  noRecord: '提供可能データがありません。',
  time: '時間',
  address: '住所',
  amount: '数',
  fees: '手数料',
  willGet: '実際に入金する',
  all: '全部',
  issueDate: '発行日',
  IssuingState: '収益の発行状態',
  nodeRevenue: 'シングルノード収益（CHEX）',
  number: '数',
  TotalRevenue: '総収益（CHEX）',
  locking: '倉庫にかぎをかける',
  unlocking: '錠をはずす',
  distributed: '発行済み',
  ndistributed: '未発行',
  success: '成功',
  fail: '失敗',
  startTime:'開始時間',
  endTime:'終了時間',
  faT:'配布時間',
  awardn:'ボーナス名',
  awardc:'貨幣を奨励する',
  awarda:'奨励の数',
  ass:'資産（USDT）',
  int:'利息（CHEX）',
  sta:'状態',
  lockTime:'ロック時間',
  lockedNum:'ロック数量（CHEX）',
  lockedpe:'ロックサイクル',
  lockRate:'年利率',
  lockExpress:'締切時間',
  notget:'受け取ることができません',
  hodlget:'未収',
  aleayget:'受け取り済み',
  roi:'収益（CHEX）',
  alis:'ロック中',
  unis:'けっけつ済み',
  month1:'ヶ月',

  Transferinto: '繰り越す',
  Transferout: '転出する',
  Transferintofor: '貨幣の口座から転入する',
  Transferoutfor: '貨幣の口座に振替する',
  operationtime: '操作時間',
  Transfermethod: 'タイプを切り替える',
  Amount: '金額',
  Operationtype: '操作の種類',
  increat: '作成中',
  inmining: '採掘中',
  inUnlock: 'ロックを解除する',
  details: '詳細',
  clubstatus: '公社状態',
  cashSatus: '資金の詳細',
  sequ: '流水らっぱ',
  Locktime: 'ロック時間',
  unLocktime: '解倉時間',
  unLocktimeType: '解凍タイプ',
  disbandStatus1: 'ユーザが終了を申請する',
  disbandStatus2: '社長が解散する',
  disbandStatus3: '採掘が終わって解倉する',

  jionAndCom: '共創に参与する',
  buildCom: '公社を創立する',
  jionCom: '公社に入る',
  propertyStatus: '資金の状態',
}
