export default {
    title:'CHA OEXの料率説明',
    title1:'チャージレート',
    title2:'取引費率',
    title3:'現金歩合',
    pay_th1:'番号付け',
    pay_th2:'貨貨幣種類類',
    pay_th3:'略称',
    pay_th4:'チャージレート',
    pay:'一方で販売手数料0.1%を徴収し、KYC 3顧客は特別な減免サービスを受けない。',
    sell:'CHEX、BTC、ETH、USDT取引エリア（一方向に販売手数料を徴収する）',
    with_th1:'番号付け',
    with_th2:'幣種',
    with_th3:'略称',
    with_th4:'手数料',
    with_th5:'単位',
    with_th6:'備考（更新時間）',
    fee_1:'KYC 1級-取引手数料0.1%',
    fee_2:'KYC 2級-取引手数料0.075%',
    fee_3:'KYC 3級-取引手数料0.05%',
    code:'ユーザの認証レベルによって、取引手数料率が異なります。',
    payYou:'取引所の取引エリアで取引手数料のお支払いを決めます。',
    rightBot:'具体的には次のとおりです',
    btcJiaoyi:'BTC取引エリアの取引手数料はBTCを徴収します。',
    ethJiaoyi:'ETH取引エリアの取引手数料はETHを徴収します。',
    usdJiaoyi:'US DT取引エリアの取引手数料はUSDTを徴収します。',
    codeJiaoyi:'CODE取引エリアの取引手数料はCODEとなります。',
    chexJiaoyi:'CHEX取引エリアの取引手数料はCHEXとなります。',
    Defree:'無料',
}