export default {
  UPA:'権限認証を知る',
  Reviewing:'審査中',
  nV: '認証なし',
  v: '認証済み',
  lg: '最終ログイン',
  sD: '認証を完了しました',
  dw: '1日あたりの限度額を提示する',
  hw: 'より低い料金と高い貨幣の限度額を享受できます。',
  cu: '連絡します',
  svd: '認証を完了しました',
  msg: 'パスワード、メッセージ、Googleの検証コードは誰にも教えないでください。私達のスタッフも含めて。',
  tA: '総資産',
  aR: '資産記録',
  d: 'チャージ',
  deal: 'チャージ可能',
  haveComplate: '認証済み',
  haveComplatePerson: 'ビデオ認証を完了しました',
  kyc1: 'まずKYC.2の認証を完了してください。',
  ylnn: 'あなたのロックポイント',
  plnn: 'プラットフォームロックノード総数',
  ptlnn: 'プラットフォーム今日のシングルノード収益',
  nm: 'ノード管理',
  node: 'ノード',
  account: 'アカウント',
  safe: '安全',
  invite: '招待',
  fee_1: '取引手数料0.1%',
  fee_2: '取引手数料0.075%',
  fee_3: '取引手数料0.05%',
  base: '基礎認証',
  person: '認証',
  video: 'ビデオ認証',
  goto: '認証',
  gu: '総資産換算',
  successful: '招待に成功しました',
  code: '私の招待番号',
  inviteFriend: '友人を招いて帰用する',
  inviteMoney:'登録してもらえますか？',
  loginRecord: 'ログインログ',
  securityRecord: '安全設定記録',
  revenueRecord: '収益記録',
  userMes:`<p>2019年1月31日までにKYCの2段階認証を完了し、</p>
  <p>1 USDTはKYCの完了を奨励する</p>
  <p>3レベル認証で、2 USDTボーナスがもらえる。</p>`,
  chexFee:'CHEXを使って取引手数料を差し引きします。',
  abolish:'キャンセル',
}
